export const AUTH_EMAIL_TYPE = {
  VERIFICATION: "verification",
  FORGOT_PASSWORD: "forgot_password",
};

export const AUTH_NAMES = {
  GENERAL: "general",
  ADMIN: "admin",
  PERMISSION: "permission",
  CAPTCHA: "captcha",
};

export const PERMISSION_TITLE = {
  MY_WORKSPACE: "MY WORKSPACE",
  USER_GROUP: "USER GROUP",
  USER_GROUP_BRAND: "Brands",
  USER_GROUP_DESIGN: "Design Firms",
  PROJECT: "PROJECTS",
  PROJECT_LIST: "Listing",
  PRODUCT: "PRODUCTS",
  PRODUCT_CATEGORY: "Categories",
  PRODUCT_BASIS: "Basis",
  PRODUCT_ATTRIBUTE: "Attributes",
  PRODUCT_CONFIGURATION: "Configurations",
  ADMINISTRATION: "ADMINISTRATION",
  ADMINISTRATION_DOCUMENTATION: "Documentations",
  ADMINISTRATION_LOCATION: "Locations",
  ADMINISTRATION_TEAM_PROFILE: "Team profiles",
  ADMINISTRATION_MESSAGE: "Messages",
  ADMINISTRATION_REVENUE: "Revenues",
};

export const BRAND_PERMISSION_TITLE = {
  MY_WORKSPACE: "MY WORKSPACE",
  PRODUCT: "PRODUCTS",
  GENERAL_INQUIRES: "GENERAL INQUIRES",
  PROJECT_TRACKING: "PROJECT TRACKING",
  ADMINISTRATION: "ADMINISTRATION",
  ADMINISTRATION_BRAND_PROFILE: "Brand Profiles",
  ADMINISTRATION_LOCATION: "Locations",
  ADMINISTRATION_TEAM_PROFILE: "Team Profiles",
  ADMINISTRATION_DISTRIBUTOR: "Distributors",
  ADMINISTRATION_MARKET_AVAILABILITY: "Market Availability",
  ADMINISTRATION_SUBSCRIPTION: "Subscription",
};

export const DESIGN_PERMISSION_TITLE = {
  MY_WORKSPACE: "MY WORKSPACE",
  MY_FAVOURITE: "MY FAVOURITE",
  PRODUCT: "PRODUCTS",
  BRAND_PRODUCT: "Brand Products",
  CUSTOM_PRODUCT: "Custom Product",
  PROJECT: "PROJECTS",
  PROJECT_LIST: "Overall Listing",
  PROJECT_BASIC: "Basic Information",
  PROJECT_ZONE: "Zone/Area/Room",
  PROJECT_CONSIDERED_PRODUCT: "Product Considered",
  PROJECT_SPECIFIED_PRODUCT: "Product Specified",
  ADMINISTRATION: "ADMINISTRATION",
  ADMINISTRATION_OFFICE_PROFILE: "Office Profile",
  ADMINISTRATION_LOCATION: "Locations",
  ADMINISTRATION_TEAM_PROFILE: "Team Profiles",
  ADMINISTRATION_MATERIAL: "Material/Product Code",
};
