export const ELECTRICAL_GEO_LOCATION = [
  {
    id: "1",
    country_name: "Abkhazia",
    country_code: "RU",
    country_calling_code: "+7 840/940",
    currency_name: "Russian ruble",
    currency_code: "RUB",
    plug_type: "C,F",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "2",
    country_name: "Afghanistan",
    country_code: "AF",
    country_calling_code: "93",
    currency_name: "Afghan Afghani",
    currency_code: "AFN",
    plug_type: "C,F",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "3",
    country_name: "Aland Islands",
    country_code: "AX",
    country_calling_code: "+358 18",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "4",
    country_name: "Albania",
    country_code: "AL",
    country_calling_code: "355",
    currency_name: "Albanian Lek",
    currency_code: "ALL",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "5",
    country_name: "Algeria",
    country_code: "DZ",
    country_calling_code: "213",
    currency_name: "Algerian Dinar",
    currency_code: "DZD",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "6",
    country_name: "American Samoa (US)",
    country_code: "AS",
    country_calling_code: "+1 684",
    currency_name: "United States Dollar",
    currency_code: "USD",
    plug_type: "A,B,F,I",
    voltage: "120 V",
    frequency: "60 Hz",
  },
  {
    id: "7",
    country_name: "Andorra",
    country_code: "AD",
    country_calling_code: "376",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "8",
    country_name: "Angola",
    country_code: "AO",
    country_calling_code: "244",
    currency_name: "Angolan Kwanza",
    currency_code: "AOA",
    plug_type: "C,F",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "9",
    country_name: "Anguilla (UK)",
    country_code: "AI",
    country_calling_code: "+1 264",
    currency_name: "East Caribbean Dollar",
    currency_code: "XCD",
    plug_type: "A",
    voltage: "110 V",
    frequency: "60 Hz",
  },
  {
    id: "10",
    country_name: "Antarctica Territories",
    country_code: "AQ",
    country_calling_code: "672",
    currency_name: "United States Dollar",
    currency_code: "USD",
    plug_type: "",
    voltage: "",
    frequency: "",
  },
  {
    id: "11",
    country_name: "Antigua and Barbuda",
    country_code: "AG",
    country_calling_code: "+1 268",
    currency_name: "East Caribbean Dollar",
    currency_code: "XCD",
    plug_type: "A,B",
    voltage: "230 V",
    frequency: "60 Hz",
  },
  {
    id: "12",
    country_name: "Argentina",
    country_code: "AR",
    country_calling_code: "54",
    currency_name: "Argentine Peso",
    currency_code: "ARS",
    plug_type: "C,I",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "13",
    country_name: "Armenia",
    country_code: "AM",
    country_calling_code: "374",
    currency_name: "Armenian Dram",
    currency_code: "AMD",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "14",
    country_name: "Artsakh (AM)",
    country_code: "AM",
    country_calling_code: "+374 47/97",
    currency_name: "Armenian Dram",
    currency_code: "AMD",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "15",
    country_name: "Aruba (NL)",
    country_code: "AW",
    country_calling_code: "297",
    currency_name: "Aruban Florin",
    currency_code: "AWG",
    plug_type: "A,B,F",
    voltage: "127 V",
    frequency: "60 Hz",
  },
  {
    id: "16",
    country_name: "Ascension Island",
    country_code: "SH",
    country_calling_code: "247",
    currency_name: "Saint Helena Pound",
    currency_code: "SHP",
    plug_type: "G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "17",
    country_name: "Australia",
    country_code: "AU",
    country_calling_code: "61",
    currency_name: "Australian Dollar",
    currency_code: "AUD",
    plug_type: "I",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "18",
    country_name: "Austria",
    country_code: "AT",
    country_calling_code: "43",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "19",
    country_name: "Azerbaijan",
    country_code: "AZ",
    country_calling_code: "994",
    currency_name: "Azerbaijan manat",
    currency_code: "AZN",
    plug_type: "C,F",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "20",
    country_name: "Bahamas",
    country_code: "BS",
    country_calling_code: "+1 242",
    currency_name: "Bahamian Dollar",
    currency_code: "BSD",
    plug_type: "A,B",
    voltage: "120 V",
    frequency: "60 Hz",
  },
  {
    id: "21",
    country_name: "Bahrain",
    country_code: "BH",
    country_calling_code: "973",
    currency_name: "Bahraini Dinar",
    currency_code: "BHD",
    plug_type: "G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "22",
    country_name: "Bangladesh",
    country_code: "BD",
    country_calling_code: "880",
    currency_name: "Bangladeshi Taka",
    currency_code: "BDT",
    plug_type: "A,C,D,G",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "23",
    country_name: "Barbados",
    country_code: "BB",
    country_calling_code: "+1 246",
    currency_name: "Barbadian Dollar",
    currency_code: "BBD",
    plug_type: "A,B",
    voltage: "115 V",
    frequency: "50 Hz",
  },
  {
    id: "24",
    country_name: "Belarus",
    country_code: "BY",
    country_calling_code: "375",
    currency_name: "Belarusian Ruble",
    currency_code: "BYN",
    plug_type: "C,F",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "25",
    country_name: "Belgium",
    country_code: "BE",
    country_calling_code: "32",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,E",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "26",
    country_name: "Belize",
    country_code: "BZ",
    country_calling_code: "501",
    currency_name: "Belize Dollar",
    currency_code: "BZD",
    plug_type: "A,B,G",
    voltage: "110 V,220 V",
    frequency: "60 Hz",
  },
  {
    id: "27",
    country_name: "Benin",
    country_code: "BJ",
    country_calling_code: "229",
    currency_name: "West African CFA Franc",
    currency_code: "XOF",
    plug_type: "C,E",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "28",
    country_name: "Bermuda (UK)",
    country_code: "BM",
    country_calling_code: "+1 441",
    currency_name: "Bermudian Dollar",
    currency_code: "BMD",
    plug_type: "A,B",
    voltage: "120 V",
    frequency: "60 Hz",
  },
  {
    id: "29",
    country_name: "Bhutan",
    country_code: "BT",
    country_calling_code: "975",
    currency_name: "Bhutanese Ngultrum",
    currency_code: "BTN",
    plug_type: "C,D,G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "30",
    country_name: "Bolivia",
    country_code: "BO",
    country_calling_code: "591",
    currency_name: "Bolivian Boliviano",
    currency_code: "BOB",
    plug_type: "A,C",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "31",
    country_name: "Bonaire (NL)",
    country_code: "BQ",
    country_calling_code: "+599 7",
    currency_name: "United States Dollar",
    currency_code: "USD",
    plug_type: "A,C",
    voltage: "127 V",
    frequency: "50 Hz",
  },
  {
    id: "32",
    country_name: "Bosnia and Herzegovina",
    country_code: "BA",
    country_calling_code: "387",
    currency_name: "Bosnia and Herzegovina convertible Mark",
    currency_code: "BAM",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "33",
    country_name: "Botswana",
    country_code: "BW",
    country_calling_code: "267",
    currency_name: "Botswana Pula",
    currency_code: "BWP",
    plug_type: "D,G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "34",
    country_name: "Bouvet Island (NO)",
    country_code: "BV",
    country_calling_code: "47",
    currency_name: "Norwegian Krone",
    currency_code: "NOK",
    plug_type: "A,B",
    voltage: "110 V",
    frequency: "60 Hz",
  },
  {
    id: "35",
    country_name: "Brazil",
    country_code: "BR",
    country_calling_code: "55",
    currency_name: "Brazilian Real",
    currency_code: "BRL",
    plug_type: "N",
    voltage: "127 V,220 V",
    frequency: "60 Hz",
  },
  {
    id: "36",
    country_name: "British Indian Ocean Territory",
    country_code: "IO",
    country_calling_code: "246",
    currency_name: "United States Dollar",
    currency_code: "USD",
    plug_type: "A,B",
    voltage: "110 V",
    frequency: "60 Hz",
  },
  {
    id: "37",
    country_name: "British Virgin Islands (UK)",
    country_code: "VG",
    country_calling_code: "+1 284",
    currency_name: "United States Dollar",
    currency_code: "USD",
    plug_type: "A,B",
    voltage: "110 V",
    frequency: "60 Hz",
  },
  {
    id: "38",
    country_name: "Brunei",
    country_code: "BN",
    country_calling_code: "673",
    currency_name: "Brunei Dollar",
    currency_code: "BND",
    plug_type: "G",
    voltage: "240 V",
    frequency: "50 Hz",
  },
  {
    id: "39",
    country_name: "Bulgaria",
    country_code: "BG",
    country_calling_code: "359",
    currency_name: "Bulgarian Lev",
    currency_code: "BGN",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "40",
    country_name: "Burkina Faso",
    country_code: "BF",
    country_calling_code: "226",
    currency_name: "West African CFA Franc",
    currency_code: "XOF",
    plug_type: "C,E",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "41",
    country_name: "Burundi",
    country_code: "BI",
    country_calling_code: "257",
    currency_name: "Burundi Franc",
    currency_code: "BIF",
    plug_type: "C,E",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "42",
    country_name: "Cambodia",
    country_code: "KH",
    country_calling_code: "855",
    currency_name: "Cambodian Riel",
    currency_code: "KHR",
    plug_type: "A,C,G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "43",
    country_name: "Cameroon",
    country_code: "CM",
    country_calling_code: "237",
    currency_name: "Central African CFA Franc",
    currency_code: "XAF",
    plug_type: "C,E",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "44",
    country_name: "Canada",
    country_code: "CA",
    country_calling_code: "1",
    currency_name: "Canadian Dollar",
    currency_code: "CAD",
    plug_type: "A,B",
    voltage: "120 V",
    frequency: "60 Hz",
  },
  {
    id: "45",
    country_name: "Cape Verde",
    country_code: "CV",
    country_calling_code: "238",
    currency_name: "Cape Verde Escudo",
    currency_code: "CVE",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "46",
    country_name: "Cayman Islands (UK)",
    country_code: "KY",
    country_calling_code: "+1 345",
    currency_name: "Cayman Islands Dollar",
    currency_code: "KYD",
    plug_type: "A,B",
    voltage: "120 V",
    frequency: "60 Hz",
  },
  {
    id: "47",
    country_name: "Central African Republic",
    country_code: "CF",
    country_calling_code: "236",
    currency_name: "Central African CFA Franc",
    currency_code: "XAF",
    plug_type: "C,E",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "48",
    country_name: "Chad",
    country_code: "TD",
    country_calling_code: "235",
    currency_name: "Central African CFA Franc",
    currency_code: "XAF",
    plug_type: "C,E,F",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "49",
    country_name: "Chile",
    country_code: "CL",
    country_calling_code: "56",
    currency_name: "Chilean Peso",
    currency_code: "CLP",
    plug_type: "C,L",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "50",
    country_name: "China",
    country_code: "CN",
    country_calling_code: "86",
    currency_name: "Chinese Yuan Renminbi",
    currency_code: "CNY",
    plug_type: "A,C,I",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "51",
    country_name: "Christmas Island",
    country_code: "CX",
    country_calling_code: "+61 891",
    currency_name: "Australian Dollar",
    currency_code: "AUD",
    plug_type: "I",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "52",
    country_name: "Cocos Islands (AU)",
    country_code: "CC",
    country_calling_code: "+61 891",
    currency_name: "Australian Dollar",
    currency_code: "AUD",
    plug_type: "I",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "53",
    country_name: "Colombia",
    country_code: "CO",
    country_calling_code: "57",
    currency_name: "Colombian Peso",
    currency_code: "COP",
    plug_type: "A,B",
    voltage: "110 V",
    frequency: "60 Hz",
  },
  {
    id: "54",
    country_name: "Comoros",
    country_code: "KM",
    country_calling_code: "269",
    currency_name: "Comorian Franc",
    currency_code: "KMF",
    plug_type: "C,E",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "55",
    country_name: "Cook Islands (NZ)",
    country_code: "CK",
    country_calling_code: "682",
    currency_name: "New Zealand Dollar",
    currency_code: "NZD",
    plug_type: "I",
    voltage: "240 V",
    frequency: "50 Hz",
  },
  {
    id: "56",
    country_name: "Costa Rica",
    country_code: "CR",
    country_calling_code: "506",
    currency_name: "Costa Rican Colon",
    currency_code: "CRC",
    plug_type: "A,B",
    voltage: "120 V",
    frequency: "60 Hz",
  },
  {
    id: "57",
    country_name: "Cote d�ivoire (Ivory Coast)",
    country_code: "CI",
    country_calling_code: "225",
    currency_name: "West African CFA Franc",
    currency_code: "XOF",
    plug_type: "C,E",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "58",
    country_name: "Croatia",
    country_code: "HR",
    country_calling_code: "385",
    currency_name: "Croatian Kuna",
    currency_code: "HRK",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "59",
    country_name: "Cuba",
    country_code: "CU",
    country_calling_code: "53",
    currency_name: "Cuban Peso",
    currency_code: "CUP",
    plug_type: "A,B,C,L",
    voltage: "110 V,220 V",
    frequency: "60 Hz",
  },
  {
    id: "60",
    country_name: "Curacao (NL)",
    country_code: "CW",
    country_calling_code: "+599 9",
    currency_name: "Netherlands Antillean Guilder",
    currency_code: "ANG",
    plug_type: "A,B",
    voltage: "127 V",
    frequency: "50 Hz",
  },
  {
    id: "61",
    country_name: "Cyprus",
    country_code: "CY",
    country_calling_code: "357",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "62",
    country_name: "Czech Republic",
    country_code: "CZ",
    country_calling_code: "420",
    currency_name: "Czech Koruna",
    currency_code: "CZK",
    plug_type: "C,E",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "63",
    country_name: "Democratic Republic of the Congo",
    country_code: "CD",
    country_calling_code: "243",
    currency_name: "Congolese Franc",
    currency_code: "CDF",
    plug_type: "C,E",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "64",
    country_name: "Denmark",
    country_code: "DK",
    country_calling_code: "45",
    currency_name: "Danish Krone",
    currency_code: "DKK",
    plug_type: "C,E,F,K",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "65",
    country_name: "Djibouti",
    country_code: "DJ",
    country_calling_code: "253",
    currency_name: "Djiboutian Franc",
    currency_code: "DJF",
    plug_type: "C,E",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "66",
    country_name: "Dominica",
    country_code: "DM",
    country_calling_code: "+1 767",
    currency_name: "East Caribbean Dollar",
    currency_code: "XCD",
    plug_type: "D,G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "67",
    country_name: "Dominican Republic",
    country_code: "DO",
    country_calling_code: "+1 809/829/849",
    currency_name: "Dominican Peso",
    currency_code: "DOP",
    plug_type: "A,B",
    voltage: "120 V",
    frequency: "60 Hz",
  },
  {
    id: "68",
    country_name: "Ecuador",
    country_code: "EC",
    country_calling_code: "593",
    currency_name: "United States Dollar",
    currency_code: "USD",
    plug_type: "A,B",
    voltage: "120 V",
    frequency: "60 Hz",
  },
  {
    id: "69",
    country_name: "Egypt",
    country_code: "EG",
    country_calling_code: "20",
    currency_name: "Egyptian Pound",
    currency_code: "EGP",
    plug_type: "C,F",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "70",
    country_name: "El Salvador",
    country_code: "SV",
    country_calling_code: "503",
    currency_name: "United States Dollar",
    currency_code: "USD",
    plug_type: "A,B",
    voltage: "120 V",
    frequency: "60 Hz",
  },
  {
    id: "71",
    country_name: "Equatorial Guinea",
    country_code: "GQ",
    country_calling_code: "240",
    currency_name: "Central African CFA Franc",
    currency_code: "XAF",
    plug_type: "C,E",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "72",
    country_name: "Eritrea",
    country_code: "ER",
    country_calling_code: "291",
    currency_name: "Eritrean Nakfa",
    currency_code: "ERN",
    plug_type: "C,L",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "73",
    country_name: "Estonia",
    country_code: "EE",
    country_calling_code: "372",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "74",
    country_name: "Eswatini (Swaziland)",
    country_code: "SZ",
    country_calling_code: "268",
    currency_name: "Swazi Lilangeni",
    currency_code: "SZL",
    plug_type: "M",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "75",
    country_name: "Ethiopia",
    country_code: "ET",
    country_calling_code: "251",
    currency_name: "Ethiopian Birr",
    currency_code: "ETB",
    plug_type: "C,F,G",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "76",
    country_name: "Falkland Islands (UK)",
    country_code: "FK",
    country_calling_code: "500",
    currency_name: "Falkland Islands Pound",
    currency_code: "FKP",
    plug_type: "G",
    voltage: "240 V",
    frequency: "50 Hz",
  },
  {
    id: "77",
    country_name: "Faroe Islands (DK)",
    country_code: "FO",
    country_calling_code: "298",
    currency_name: "Danish Krone",
    currency_code: "DKK",
    plug_type: "C,E,F,K",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "78",
    country_name: "Fiji",
    country_code: "FJ",
    country_calling_code: "679",
    currency_name: "Fijian Dollar",
    currency_code: "FJD",
    plug_type: "I",
    voltage: "240 V",
    frequency: "50 Hz",
  },
  {
    id: "79",
    country_name: "Finland",
    country_code: "FI",
    country_calling_code: "358",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "80",
    country_name: "France",
    country_code: "FR",
    country_calling_code: "33",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,E",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "81",
    country_name: "French Guiana (FR)",
    country_code: "GF",
    country_calling_code: "594",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,E",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "82",
    country_name: "French Polynesia (FR)",
    country_code: "PF",
    country_calling_code: "689",
    currency_name: "CFP Franc",
    currency_code: "XPF",
    plug_type: "A,B,E",
    voltage: "110 V,220 V",
    frequency: "50 Hz,60 Hz",
  },
  {
    id: "83",
    country_name: "French Southern Territories (FR)",
    country_code: "TF",
    country_calling_code: "262",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "E",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "84",
    country_name: "Gabon",
    country_code: "GA",
    country_calling_code: "241",
    currency_name: "Central African CFA Franc",
    currency_code: "XAF",
    plug_type: "C,E",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "85",
    country_name: "Gambia",
    country_code: "GM",
    country_calling_code: "220",
    currency_name: "Gambian Dalasi",
    currency_code: "GMD",
    plug_type: "G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "86",
    country_name: "Georgia",
    country_code: "GE",
    country_calling_code: "995",
    currency_name: "Georgian Lari",
    currency_code: "GEL",
    plug_type: "C,F",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "87",
    country_name: "Germany",
    country_code: "DE",
    country_calling_code: "49",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "88",
    country_name: "Ghana",
    country_code: "GH",
    country_calling_code: "233",
    currency_name: "Ghanaian Cedi",
    currency_code: "GHS",
    plug_type: "D,G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "89",
    country_name: "Gibraltar (UK)",
    country_code: "GI",
    country_calling_code: "350",
    currency_name: "Gibraltar Pound",
    currency_code: "GIP",
    plug_type: "G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "90",
    country_name: "Greece",
    country_code: "GR",
    country_calling_code: "30",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "91",
    country_name: "Greenland (DK)",
    country_code: "GL",
    country_calling_code: "299",
    currency_name: "Danish Krone",
    currency_code: "DKK",
    plug_type: "C,E,F,K",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "92",
    country_name: "Grenada",
    country_code: "GD",
    country_calling_code: "+1 473",
    currency_name: "East Caribbean Dollar",
    currency_code: "XCD",
    plug_type: "G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "93",
    country_name: "Guadeloupe (FR)",
    country_code: "GP",
    country_calling_code: "590",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,E",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "94",
    country_name: "Guam (US)",
    country_code: "GU",
    country_calling_code: "+1 671",
    currency_name: "United States Dollar",
    currency_code: "USD",
    plug_type: "A,B",
    voltage: "110 V",
    frequency: "60 Hz",
  },
  {
    id: "95",
    country_name: "Guatemala",
    country_code: "GT",
    country_calling_code: "502",
    currency_name: "Guatemalan Quetzal",
    currency_code: "GTQ",
    plug_type: "A,B",
    voltage: "120 V",
    frequency: "60 Hz",
  },
  {
    id: "96",
    country_name: "Guernsey (UK)",
    country_code: "GG",
    country_calling_code: "+44 1481",
    currency_name: "Guernsey Pound",
    currency_code: "GGP",
    plug_type: "C,G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "97",
    country_name: "Guinea",
    country_code: "GN",
    country_calling_code: "224",
    currency_name: "Guinean Franc",
    currency_code: "GNF",
    plug_type: "C,F",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "98",
    country_name: "Guinea-Bissau",
    country_code: "GW",
    country_calling_code: "245",
    currency_name: "West African CFA Franc",
    currency_code: "XOF",
    plug_type: "C,E,F",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "99",
    country_name: "Guyana",
    country_code: "GY",
    country_calling_code: "592",
    currency_name: "Guyanese Dollar",
    currency_code: "GYD",
    plug_type: "A,B,D,G",
    voltage: "240 V",
    frequency: "60 Hz",
  },
  {
    id: "100",
    country_name: "Haiti",
    country_code: "HT",
    country_calling_code: "509",
    currency_name: "Haitian Gourde",
    currency_code: "HTG",
    plug_type: "A,B",
    voltage: "110 V",
    frequency: "60 Hz",
  },
  {
    id: "101",
    country_name: "Heard Island and McDonald Islands (AU)",
    country_code: "HM",
    country_calling_code: "0",
    currency_name: "Australian Dollar",
    currency_code: "AUD",
    plug_type: "I",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "102",
    country_name: "Honduras",
    country_code: "HN",
    country_calling_code: "504",
    currency_name: "Honduran Lempira",
    currency_code: "HNL",
    plug_type: "A,B",
    voltage: "120 V",
    frequency: "60 Hz",
  },
  {
    id: "103",
    country_name: "Hong Kong (CN)",
    country_code: "HK",
    country_calling_code: "852",
    currency_name: "Hong Kong Dollar",
    currency_code: "HKD",
    plug_type: "G",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "104",
    country_name: "Hungary",
    country_code: "HU",
    country_calling_code: "36",
    currency_name: "Hungarian Forint",
    currency_code: "HUF",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "105",
    country_name: "Iceland",
    country_code: "IS",
    country_calling_code: "354",
    currency_name: "Icelandic Krona",
    currency_code: "ISK",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "106",
    country_name: "India",
    country_code: "IN",
    country_calling_code: "91",
    currency_name: "Indian Rupee",
    currency_code: "INR",
    plug_type: "C,D,M",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "107",
    country_name: "Indonesia",
    country_code: "ID",
    country_calling_code: "62",
    currency_name: "Indonesian Rupiah",
    currency_code: "IDR",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "108",
    country_name: "Iran",
    country_code: "IR",
    country_calling_code: "98",
    currency_name: "Iranian Rial",
    currency_code: "IRR",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "109",
    country_name: "Iraq",
    country_code: "IQ",
    country_calling_code: "964",
    currency_name: "Iraqi Dinar",
    currency_code: "IQD",
    plug_type: "C,D,G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "110",
    country_name: "Ireland",
    country_code: "IE",
    country_calling_code: "353",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "111",
    country_name: "Isle of Man (UK)",
    country_code: "IM",
    country_calling_code: "+44 1624",
    currency_name: "Manx Pound",
    currency_code: "IMP",
    plug_type: "C,G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "112",
    country_name: "Israel",
    country_code: "IL",
    country_calling_code: "972",
    currency_name: "Israeli New Shekel",
    currency_code: "ILS",
    plug_type: "C,H",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "113",
    country_name: "Italy",
    country_code: "IT",
    country_calling_code: "39",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,F,L",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "114",
    country_name: "Jamaica",
    country_code: "JM",
    country_calling_code: "+1 876/658",
    currency_name: "Jamaican Dollar",
    currency_code: "JMD",
    plug_type: "A,B",
    voltage: "110 V",
    frequency: "50 Hz",
  },
  {
    id: "115",
    country_name: "Japan",
    country_code: "JP",
    country_calling_code: "81",
    currency_name: "Japanese Yen",
    currency_code: "JPY",
    plug_type: "A,B",
    voltage: "100 V",
    frequency: "50 Hz,60 Hz",
  },
  {
    id: "116",
    country_name: "Jersey (UK)",
    country_code: "JE",
    country_calling_code: "+44 1534",
    currency_name: "Jersey Pound",
    currency_code: "JEP",
    plug_type: "C,G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "117",
    country_name: "Jordan",
    country_code: "JO",
    country_calling_code: "962",
    currency_name: "Jordanian Dinar",
    currency_code: "JOD",
    plug_type: "C,D,F,G,J",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "118",
    country_name: "Kazakhstan",
    country_code: "KZ",
    country_calling_code: "+7 6/7",
    currency_name: "Kazakhstani Tenge",
    currency_code: "KZT",
    plug_type: "C,F",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "119",
    country_name: "Kenya",
    country_code: "KE",
    country_calling_code: "254",
    currency_name: "Kenyan Shilling",
    currency_code: "KES",
    plug_type: "G",
    voltage: "240 V",
    frequency: "50 Hz",
  },
  {
    id: "120",
    country_name: "Kiribati",
    country_code: "KI",
    country_calling_code: "686",
    currency_name: "Australian Dollar",
    currency_code: "AUD",
    plug_type: "I",
    voltage: "240 V",
    frequency: "50 Hz",
  },
  {
    id: "121",
    country_name: "Kosovo",
    country_code: "XK",
    country_calling_code: "383",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "122",
    country_name: "Kuwait",
    country_code: "KW",
    country_calling_code: "965",
    currency_name: "Kuwaiti Dinar",
    currency_code: "KWD",
    plug_type: "G",
    voltage: "240 V",
    frequency: "50 Hz",
  },
  {
    id: "123",
    country_name: "Kyrgyzstan",
    country_code: "KG",
    country_calling_code: "996",
    currency_name: "Kyrgyzstani SOM",
    currency_code: "KGS",
    plug_type: "C,F",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "124",
    country_name: "Laos",
    country_code: "LA",
    country_calling_code: "856",
    currency_name: "Lao Kip",
    currency_code: "LAK",
    plug_type: "A,B,C,E,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "125",
    country_name: "Latvia",
    country_code: "LV",
    country_calling_code: "371",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "126",
    country_name: "Lebanon",
    country_code: "LB",
    country_calling_code: "961",
    currency_name: "Lebanese Pound",
    currency_code: "LBP",
    plug_type: "C,D,G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "127",
    country_name: "Lesotho",
    country_code: "LS",
    country_calling_code: "266",
    currency_name: "Lesotho Loti",
    currency_code: "LSL",
    plug_type: "M",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "128",
    country_name: "Liberia",
    country_code: "LR",
    country_calling_code: "231",
    currency_name: "Liberian Dollar",
    currency_code: "LRD",
    plug_type: "A,B,C,F",
    voltage: "120 V,220 V",
    frequency: "60 Hz",
  },
  {
    id: "129",
    country_name: "Libya",
    country_code: "LY",
    country_calling_code: "218",
    currency_name: "Libyan Dinar",
    currency_code: "LYD",
    plug_type: "C,L",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "130",
    country_name: "Liechtenstein",
    country_code: "LI",
    country_calling_code: "423",
    currency_name: "Swiss Franc",
    currency_code: "CHF",
    plug_type: "C,J",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "131",
    country_name: "Lithuania",
    country_code: "LT",
    country_calling_code: "370",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "132",
    country_name: "Luxembourg",
    country_code: "LU",
    country_calling_code: "352",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "133",
    country_name: "Macao (CN)",
    country_code: "MO",
    country_calling_code: "853",
    currency_name: "Macanese Pataca",
    currency_code: "MOP",
    plug_type: "G",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "134",
    country_name: "Macedonia",
    country_code: "MK",
    country_calling_code: "389",
    currency_name: "Macedonian Denar",
    currency_code: "MKD",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "135",
    country_name: "Madagascar",
    country_code: "MG",
    country_calling_code: "261",
    currency_name: "Malagasy Ariary",
    currency_code: "MGA",
    plug_type: "C,E",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "136",
    country_name: "Malawi",
    country_code: "MW",
    country_calling_code: "265",
    currency_name: "Malawian Kwacha",
    currency_code: "MWK",
    plug_type: "G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "137",
    country_name: "Malaysia",
    country_code: "MY",
    country_calling_code: "60",
    currency_name: "Malaysian Ringgit",
    currency_code: "MYR",
    plug_type: "G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "138",
    country_name: "Maldives",
    country_code: "MV",
    country_calling_code: "960",
    currency_name: "Maldivian Rufiyaa",
    currency_code: "MVR",
    plug_type: "C,D,G,L",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "139",
    country_name: "Mali",
    country_code: "ML",
    country_calling_code: "223",
    currency_name: "West African CFA Franc",
    currency_code: "XOF",
    plug_type: "C,E",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "140",
    country_name: "Malta",
    country_code: "MT",
    country_calling_code: "356",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "141",
    country_name: "Marshall Islands",
    country_code: "MH",
    country_calling_code: "692",
    currency_name: "United States Dollar",
    currency_code: "USD",
    plug_type: "A,B",
    voltage: "120 V",
    frequency: "60 Hz",
  },
  {
    id: "142",
    country_name: "Martinique (FR)",
    country_code: "MQ",
    country_calling_code: "596",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,E",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "143",
    country_name: "Mauritania",
    country_code: "MR",
    country_calling_code: "222",
    currency_name: "Mauritanian Ouguiya",
    currency_code: "MRU",
    plug_type: "C,E,F",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "144",
    country_name: "Mauritius",
    country_code: "MU",
    country_calling_code: "230",
    currency_name: "Mauritian Rupee",
    currency_code: "MUR",
    plug_type: "C,G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "145",
    country_name: "Mayotte (FR)",
    country_code: "YT",
    country_calling_code: "+262 269/639",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,E",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "146",
    country_name: "Mexico",
    country_code: "MX",
    country_calling_code: "52",
    currency_name: "Mexican Peso",
    currency_code: "MXN",
    plug_type: "A,B",
    voltage: "127 V",
    frequency: "60 Hz",
  },
  {
    id: "147",
    country_name: "Micronesia",
    country_code: "FM",
    country_calling_code: "691",
    currency_name: "United States Dollar",
    currency_code: "USD",
    plug_type: "A,B",
    voltage: "120 V",
    frequency: "60 Hz",
  },
  {
    id: "148",
    country_name: "Moldova",
    country_code: "MD",
    country_calling_code: "373",
    currency_name: "Moldovan Leu",
    currency_code: "MDL",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "149",
    country_name: "Monaco",
    country_code: "MC",
    country_calling_code: "377",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,E,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "150",
    country_name: "Mongolia",
    country_code: "MN",
    country_calling_code: "976",
    currency_name: "Mongolian Tugrik",
    currency_code: "MNT",
    plug_type: "Universal A/C, Universal A/B/C/D/E/F/G/I/O",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "151",
    country_name: "Montenegro",
    country_code: "ME",
    country_calling_code: "382",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "152",
    country_name: "Montserrat (UK)",
    country_code: "MS",
    country_calling_code: "+1 664",
    currency_name: "East Caribbean Dollar",
    currency_code: "XCD",
    plug_type: "A,B",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "153",
    country_name: "Morocco",
    country_code: "MA",
    country_calling_code: "212",
    currency_name: "Moroccan Dirham",
    currency_code: "MAD",
    plug_type: "C,E",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "154",
    country_name: "Mozambique",
    country_code: "MZ",
    country_calling_code: "258",
    currency_name: "Mozambican Metical",
    currency_code: "MZN",
    plug_type: "C,F,M",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "155",
    country_name: "Myanmar (Burma)",
    country_code: "MM",
    country_calling_code: "95",
    currency_name: "Myanmar Kyat",
    currency_code: "MMK",
    plug_type: "A,C,D,G,I",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "156",
    country_name: "Namibia",
    country_code: "NA",
    country_calling_code: "264",
    currency_name: "Namibian Dollar",
    currency_code: "NAD",
    plug_type: "D,M",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "157",
    country_name: "Nauru",
    country_code: "NR",
    country_calling_code: "674",
    currency_name: "Australian Dollar",
    currency_code: "AUD",
    plug_type: "I",
    voltage: "240 V",
    frequency: "50 Hz",
  },
  {
    id: "158",
    country_name: "Nepal",
    country_code: "NP",
    country_calling_code: "977",
    currency_name: "Nepalese Rupee",
    currency_code: "NPR",
    plug_type: "C,D,M",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "159",
    country_name: "Netherlands",
    country_code: "NL",
    country_calling_code: "31",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "160",
    country_name: "Netherlands Antilles (NL)",
    country_code: "AN",
    country_calling_code: "599",
    currency_name: "Netherlands Antilles Guilder",
    currency_code: "ANG",
    plug_type: "A,B",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "161",
    country_name: "New Caledonia (FR)",
    country_code: "NC",
    country_calling_code: "687",
    currency_name: "CFP Franc",
    currency_code: "XPF",
    plug_type: "C,E",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "162",
    country_name: "New Zealand",
    country_code: "NZ",
    country_calling_code: "64",
    currency_name: "New Zealand Dollar",
    currency_code: "NZD",
    plug_type: "I",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "163",
    country_name: "Nicaragua",
    country_code: "NI",
    country_calling_code: "505",
    currency_name: "Nicaraguan Cordoba",
    currency_code: "NIO",
    plug_type: "A,B",
    voltage: "120 V",
    frequency: "60 Hz",
  },
  {
    id: "164",
    country_name: "Niger",
    country_code: "NE",
    country_calling_code: "227",
    currency_name: "West African CFA Franc",
    currency_code: "XOF",
    plug_type: "C,D,E",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "165",
    country_name: "Nigeria",
    country_code: "NG",
    country_calling_code: "234",
    currency_name: "Nigerian Naira",
    currency_code: "NGN",
    plug_type: "D,G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "166",
    country_name: "Niue (NZ)",
    country_code: "NU",
    country_calling_code: "683",
    currency_name: "New Zealand Dollar",
    currency_code: "NZD",
    plug_type: "I",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "167",
    country_name: "Norfolk Island (AU)",
    country_code: "NF",
    country_calling_code: "+672 3",
    currency_name: "Australian Dollar",
    currency_code: "AUD",
    plug_type: "I",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "168",
    country_name: "North Korea",
    country_code: "KP",
    country_calling_code: "850",
    currency_name: "North Korean Won",
    currency_code: "KPW",
    plug_type: "C,F",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "169",
    country_name: "Northern Mariana Islands (US)",
    country_code: "MP",
    country_calling_code: "+1 670",
    currency_name: "United States Dollar",
    currency_code: "USD",
    plug_type: "A,B",
    voltage: "120 V",
    frequency: "60 Hz",
  },
  {
    id: "170",
    country_name: "Norway",
    country_code: "NO",
    country_calling_code: "47",
    currency_name: "Norwegian Krone",
    currency_code: "NOK",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "171",
    country_name: "Oman",
    country_code: "OM",
    country_calling_code: "968",
    currency_name: "Omani Rial",
    currency_code: "OMR",
    plug_type: "G",
    voltage: "240 V",
    frequency: "50 Hz",
  },
  {
    id: "172",
    country_name: "Pakistan",
    country_code: "PK",
    country_calling_code: "92",
    currency_name: "Pakistani Rupee",
    currency_code: "PKR",
    plug_type: "C,D",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "173",
    country_name: "Palau",
    country_code: "PW",
    country_calling_code: "680",
    currency_name: "United States Dollar",
    currency_code: "USD",
    plug_type: "A,B",
    voltage: "120 V",
    frequency: "60 Hz",
  },
  {
    id: "174",
    country_name: "Palestine",
    country_code: "PS",
    country_calling_code: "970",
    currency_name: "Israeli New Shekel",
    currency_code: "ILS",
    plug_type: "C,H",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "175",
    country_name: "Panama",
    country_code: "PA",
    country_calling_code: "507",
    currency_name: "United States Dollar",
    currency_code: "USD",
    plug_type: "A,B",
    voltage: "120 V",
    frequency: "60 Hz",
  },
  {
    id: "176",
    country_name: "Papua New Guinea",
    country_code: "PG",
    country_calling_code: "675",
    currency_name: "Papua New Guinean Kina",
    currency_code: "PGK",
    plug_type: "I",
    voltage: "240 V",
    frequency: "50 Hz",
  },
  {
    id: "177",
    country_name: "Paraguay",
    country_code: "PY",
    country_calling_code: "595",
    currency_name: "Paraguayan Guarani",
    currency_code: "PYG",
    plug_type: "A,C",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "178",
    country_name: "Peru",
    country_code: "PE",
    country_calling_code: "51",
    currency_name: "Peruvian Sol",
    currency_code: "PEN",
    plug_type: "A,B,C",
    voltage: "220 V",
    frequency: "60 Hz",
  },
  {
    id: "179",
    country_name: "Philippines",
    country_code: "PH",
    country_calling_code: "63",
    currency_name: "Philippine Peso",
    currency_code: "PHP",
    plug_type: "A,B,C",
    voltage: "220 V",
    frequency: "60 Hz",
  },
  {
    id: "180",
    country_name: "Pitcairn Islands (UK)",
    country_code: "PN",
    country_calling_code: "64",
    currency_name: "New Zealand Dollar",
    currency_code: "NZD",
    plug_type: "I",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "181",
    country_name: "Poland",
    country_code: "PL",
    country_calling_code: "48",
    currency_name: "Polish Zloty",
    currency_code: "PLN",
    plug_type: "C,E",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "182",
    country_name: "Portugal",
    country_code: "PT",
    country_calling_code: "351",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "183",
    country_name: "Puerto Rico (US)",
    country_code: "PR",
    country_calling_code: "+1 787/939",
    currency_name: "United States Dollar",
    currency_code: "USD",
    plug_type: "A,B",
    voltage: "120 V",
    frequency: "60 Hz",
  },
  {
    id: "184",
    country_name: "Qatar",
    country_code: "QA",
    country_calling_code: "974",
    currency_name: "Qatari Riyal",
    currency_code: "QAR",
    plug_type: "G",
    voltage: "240 V",
    frequency: "50 Hz",
  },
  {
    id: "185",
    country_name: "Republic of the Congo",
    country_code: "CG",
    country_calling_code: "242",
    currency_name: "Central African CFA Franc",
    currency_code: "XAF",
    plug_type: "C,D,E",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "186",
    country_name: "Reunion (FR)",
    country_code: "RE",
    country_calling_code: "262",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,E",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "187",
    country_name: "Romania",
    country_code: "RO",
    country_calling_code: "40",
    currency_name: "Romanian Leu",
    currency_code: "RON",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "188",
    country_name: "Russia",
    country_code: "RU",
    country_calling_code: "7",
    currency_name: "Russian Ruble",
    currency_code: "RUB",
    plug_type: "C,F",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "189",
    country_name: "Rwanda",
    country_code: "RW",
    country_calling_code: "250",
    currency_name: "Rwandan Franc",
    currency_code: "RWF",
    plug_type: "C,E,F,G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "190",
    country_name: "Saba (NL)",
    country_code: "BQ",
    country_calling_code: "+599 4",
    currency_name: "United States Dollar",
    currency_code: "USD",
    plug_type: "A,B",
    voltage: "110 V",
    frequency: "60 Hz",
  },
  {
    id: "191",
    country_name: "Saint Barthelemy (FR)",
    country_code: "BL",
    country_calling_code: "590",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,E",
    voltage: "230 V",
    frequency: "60 Hz",
  },
  {
    id: "192",
    country_name: "Saint Eustatius (NL)",
    country_code: "BQ",
    country_calling_code: "+599 3",
    currency_name: "United States Dollar",
    currency_code: "USD",
    plug_type: "A,B,C,F",
    voltage: "110 V,220 V",
    frequency: "60 Hz",
  },
  {
    id: "193",
    country_name: "Saint Helena (UK)",
    country_code: "SH",
    country_calling_code: "290",
    currency_name: "Saint Helena Pound",
    currency_code: "SHP",
    plug_type: "G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "194",
    country_name: "Saint Kitts and Nevis",
    country_code: "KN",
    country_calling_code: "+1 869",
    currency_name: "East Caribbean Dollar",
    currency_code: "XCD",
    plug_type: "D,G",
    voltage: "230 V",
    frequency: "60 Hz",
  },
  {
    id: "195",
    country_name: "Saint Lucia",
    country_code: "LC",
    country_calling_code: "+1 758",
    currency_name: "East Caribbean Dollar",
    currency_code: "XCD",
    plug_type: "G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "196",
    country_name: "Saint Maarten (NL)",
    country_code: "SX",
    country_calling_code: "+1 721",
    currency_name: "Netherlands Antilles Guilder",
    currency_code: "ANG",
    plug_type: "A,B",
    voltage: "110 V",
    frequency: "60 Hz",
  },
  {
    id: "197",
    country_name: "Saint Martin (FR)",
    country_code: "MF",
    country_calling_code: "590",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,E",
    voltage: "220 V",
    frequency: "60 Hz",
  },
  {
    id: "198",
    country_name: "Saint Pierre and Miquelon (FR)",
    country_code: "PM",
    country_calling_code: "508",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,E",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "199",
    country_name: "Saint Vincent and the Grenadines",
    country_code: "VC",
    country_calling_code: "+1 784",
    currency_name: "East Caribbean Dollar",
    currency_code: "XCD",
    plug_type: "A,B,G",
    voltage: "110 V,230 V",
    frequency: "50 Hz",
  },
  {
    id: "200",
    country_name: "Samoa",
    country_code: "WS",
    country_calling_code: "685",
    currency_name: "Samoan Tala",
    currency_code: "WST",
    plug_type: "I",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "201",
    country_name: "San Marino",
    country_code: "SM",
    country_calling_code: "378",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,F,L",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "202",
    country_name: "Sao Tome and Principe",
    country_code: "ST",
    country_calling_code: "239",
    currency_name: "Sao Tome and Principe Dobra",
    currency_code: "STN",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "203",
    country_name: "Saudi Arabia",
    country_code: "SA",
    country_calling_code: "966",
    currency_name: "Saudi Arabian Riyal",
    currency_code: "SAR",
    plug_type: "G",
    voltage: "220 V",
    frequency: "60 Hz",
  },
  {
    id: "204",
    country_name: "Senegal",
    country_code: "SN",
    country_calling_code: "221",
    currency_name: "West African CFA Franc",
    currency_code: "XOF",
    plug_type: "C,D,E",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "205",
    country_name: "Serbia",
    country_code: "CS",
    country_calling_code: "382",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "206",
    country_name: "Seychelles",
    country_code: "SC",
    country_calling_code: "248",
    currency_name: "Seychellois Rupee",
    currency_code: "SCR",
    plug_type: "G",
    voltage: "240 V",
    frequency: "50 Hz",
  },
  {
    id: "207",
    country_name: "Sierra Leone",
    country_code: "SL",
    country_calling_code: "232",
    currency_name: "Sierra Leonean Leone",
    currency_code: "SLL",
    plug_type: "D,G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "208",
    country_name: "Singapore",
    country_code: "SG",
    country_calling_code: "65",
    currency_name: "Singapore Dollar",
    currency_code: "SGD",
    plug_type: "G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "209",
    country_name: "Slovakia",
    country_code: "SK",
    country_calling_code: "421",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,E",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "210",
    country_name: "Slovenia",
    country_code: "SI",
    country_calling_code: "386",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "211",
    country_name: "Solomon Islands",
    country_code: "SB",
    country_calling_code: "677",
    currency_name: "Solomon Islands Dollar",
    currency_code: "SBD",
    plug_type: "G,I",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "212",
    country_name: "Somalia",
    country_code: "SO",
    country_calling_code: "252",
    currency_name: "Somali Shilling",
    currency_code: "SOS",
    plug_type: "Universal A/B/C/G, Universal A/B/C/D/E/F/G/I/O",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "213",
    country_name: "South Africa",
    country_code: "ZA",
    country_calling_code: "27",
    currency_name: "South African Rand",
    currency_code: "ZAR",
    plug_type: "C,M,N",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "214",
    country_name: "South Georgia and the South Sandwich Islands (UK)",
    country_code: "GS",
    country_calling_code: "500",
    currency_name: "Falkland Islands Pound",
    currency_code: "FKP",
    plug_type: "C,F",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "215",
    country_name: "South Korea",
    country_code: "KR",
    country_calling_code: "82",
    currency_name: "South Korean Won",
    currency_code: "KRW",
    plug_type: "C,F",
    voltage: "220 V",
    frequency: "60 Hz",
  },
  {
    id: "216",
    country_name: "South Ossetia",
    country_code: "GE",
    country_calling_code: "+995 34",
    currency_name: "Russian Ruble",
    currency_code: "RUB",
    plug_type: "C,F",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "217",
    country_name: "South Sudan",
    country_code: "SS",
    country_calling_code: "211",
    currency_name: "South Sudanese Pound",
    currency_code: "SSP",
    plug_type: "C,D",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "218",
    country_name: "Spain",
    country_code: "ES",
    country_calling_code: "34",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "219",
    country_name: "Sri Lanka",
    country_code: "LK",
    country_calling_code: "94",
    currency_name: "Sri Lankan Rupee",
    currency_code: "LKR",
    plug_type: "D,G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "220",
    country_name: "Sudan",
    country_code: "SD",
    country_calling_code: "249",
    currency_name: "Sudanese Pound",
    currency_code: "SDG",
    plug_type: "C,D",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "221",
    country_name: "Suriname",
    country_code: "SR",
    country_calling_code: "597",
    currency_name: "Surinamese Dollar",
    currency_code: "SRD",
    plug_type: "A,B,C,F",
    voltage: "127 V,220 V",
    frequency: "60 Hz",
  },
  {
    id: "222",
    country_name: "Svalbard and Jan Mayen (NO)",
    country_code: "SJ",
    country_calling_code: "47",
    currency_name: "Norwegian Krone",
    currency_code: "NOK",
    plug_type: "F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "223",
    country_name: "Sweden",
    country_code: "SE",
    country_calling_code: "46",
    currency_name: "Swedish Krona",
    currency_code: "SEK",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "224",
    country_name: "Switzerland",
    country_code: "CH",
    country_calling_code: "41",
    currency_name: "Swiss Franc",
    currency_code: "CHF",
    plug_type: "C,J",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "225",
    country_name: "Syria",
    country_code: "SY",
    country_calling_code: "963",
    currency_name: "Syrian Pound",
    currency_code: "SYP",
    plug_type: "C,E,L",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "226",
    country_name: "Taiwan (CN)",
    country_code: "TW",
    country_calling_code: "886",
    currency_name: "New Taiwan Dollar",
    currency_code: "TWD",
    plug_type: "A,B",
    voltage: "110 V",
    frequency: "60 Hz",
  },
  {
    id: "227",
    country_name: "Tajikistan",
    country_code: "TJ",
    country_calling_code: "992",
    currency_name: "Tajikistani Somoni",
    currency_code: "TJS",
    plug_type: "C,F",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "228",
    country_name: "Tanzania",
    country_code: "TZ",
    country_calling_code: "255",
    currency_name: "Tanzanian Shilling",
    currency_code: "TZS",
    plug_type: "D,G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "229",
    country_name: "Thailand",
    country_code: "TH",
    country_calling_code: "66",
    currency_name: "Thai Baht",
    currency_code: "THB",
    plug_type: "A,B,C,O",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "230",
    country_name: "Timor-Leste (East Timor)",
    country_code: "TL",
    country_calling_code: "670",
    currency_name: "United States Dollar",
    currency_code: "USD",
    plug_type: "C,E,F,I",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "231",
    country_name: "Togo",
    country_code: "TG",
    country_calling_code: "228",
    currency_name: "West African CFA Franc",
    currency_code: "XOF",
    plug_type: "C,E",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "232",
    country_name: "Tokelau (NZ)",
    country_code: "TK",
    country_calling_code: "690",
    currency_name: "New Zealand Dollar",
    currency_code: "NZD",
    plug_type: "I",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "233",
    country_name: "Tonga",
    country_code: "TO",
    country_calling_code: "676",
    currency_name: "Tongan Pa�anga",
    currency_code: "TOP",
    plug_type: "I",
    voltage: "240 V",
    frequency: "50 Hz",
  },
  {
    id: "234",
    country_name: "Trinidad and Tobago",
    country_code: "TT",
    country_calling_code: "+1 868",
    currency_name: "Trinidad and Tobago Dollar",
    currency_code: "TTD",
    plug_type: "A,B",
    voltage: "115 V",
    frequency: "60 Hz",
  },
  {
    id: "235",
    country_name: "Tristan da Cunha (UK)",
    country_code: "SH",
    country_calling_code: "+290 8",
    currency_name: "Pound Sterling",
    currency_code: "GBP",
    plug_type: "G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "236",
    country_name: "Tunisia",
    country_code: "TN",
    country_calling_code: "216",
    currency_name: "Tunisian Dinar",
    currency_code: "TND",
    plug_type: "C,E",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "237",
    country_name: "Turkey",
    country_code: "TR",
    country_calling_code: "90",
    currency_name: "Turkish Lira",
    currency_code: "TRY",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "238",
    country_name: "Turkmenistan",
    country_code: "TM",
    country_calling_code: "993",
    currency_name: "Turkmen Manat",
    currency_code: "TMT",
    plug_type: "C,F",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "239",
    country_name: "Turks and Caicos Islands (UK)",
    country_code: "TC",
    country_calling_code: "+1 649",
    currency_name: "United States Dollar",
    currency_code: "USD",
    plug_type: "A,B",
    voltage: "120 V",
    frequency: "60 Hz",
  },
  {
    id: "240",
    country_name: "Tuvalu",
    country_code: "TV",
    country_calling_code: "688",
    currency_name: "Australian Dollar",
    currency_code: "AUD",
    plug_type: "I",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "241",
    country_name: "Uganda",
    country_code: "UG",
    country_calling_code: "256",
    currency_name: "Ugandan Shilling",
    currency_code: "UGX",
    plug_type: "G",
    voltage: "240 V",
    frequency: "50 Hz",
  },
  {
    id: "242",
    country_name: "Ukraine",
    country_code: "UA",
    country_calling_code: "380",
    currency_name: "Ukrainian Hryvnia",
    currency_code: "UAH",
    plug_type: "C,F",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "243",
    country_name: "United Arab Emirates",
    country_code: "AE",
    country_calling_code: "971",
    currency_name: "UAE Dirham",
    currency_code: "AED",
    plug_type: "G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "244",
    country_name: "United Kingdom",
    country_code: "GB",
    country_calling_code: "44",
    currency_name: "Pound Sterling",
    currency_code: "GBP",
    plug_type: "G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "245",
    country_name: "United States",
    country_code: "US",
    country_calling_code: "1",
    currency_name: "United States Dollar",
    currency_code: "USD",
    plug_type: "A,B",
    voltage: "120 V",
    frequency: "60 Hz",
  },
  {
    id: "246",
    country_name: "United States Minor Outlying Islands",
    country_code: "UM",
    country_calling_code: "246",
    currency_name: "United States Dollar",
    currency_code: "USD",
    plug_type: "A,B",
    voltage: "120 V",
    frequency: "60 Hz",
  },
  {
    id: "247",
    country_name: "United States Virgin Islands",
    country_code: "VI",
    country_calling_code: "+1 340",
    currency_name: "United States Dollar",
    currency_code: "USD",
    plug_type: "A,B",
    voltage: "110 V",
    frequency: "60 Hz",
  },
  {
    id: "248",
    country_name: "Uruguay",
    country_code: "UY",
    country_calling_code: "598",
    currency_name: "Uruguayan Peso",
    currency_code: "UYU",
    plug_type: "C,F,L",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "249",
    country_name: "Uzbekistan",
    country_code: "UZ",
    country_calling_code: "998",
    currency_name: "Uzbekistani Som",
    currency_code: "UZS",
    plug_type: "C,F",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "250",
    country_name: "Vanuatu",
    country_code: "VU",
    country_calling_code: "678",
    currency_name: "Vanuatu Vatu",
    currency_code: "VUV",
    plug_type: "I",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "251",
    country_name: "Vatican",
    country_code: "VA",
    country_calling_code: "379",
    currency_name: "European Euro",
    currency_code: "EUR",
    plug_type: "C,F,L",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "252",
    country_name: "Venezuela",
    country_code: "VE",
    country_calling_code: "58",
    currency_name: "Venezuelan Bolivar",
    currency_code: "VES",
    plug_type: "A,B",
    voltage: "120 V",
    frequency: "60 Hz",
  },
  {
    id: "253",
    country_name: "Vietnam",
    country_code: "VN",
    country_calling_code: "84",
    currency_name: "Vietnamese Dong",
    currency_code: "VND",
    plug_type: "A,B,C",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "254",
    country_name: "Wallis and Futuna (FR)",
    country_code: "WF",
    country_calling_code: "681",
    currency_name: "CFP Franc",
    currency_code: "XPF",
    plug_type: "C,E",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "255",
    country_name: "Western Sahara",
    country_code: "EH",
    country_calling_code: "212",
    currency_name: "Moroccan Dirham",
    currency_code: "MAD",
    plug_type: "C,E",
    voltage: "220 V",
    frequency: "50 Hz",
  },
  {
    id: "256",
    country_name: "Yemen",
    country_code: "YE",
    country_calling_code: "967",
    currency_name: "Yemeni Rial",
    currency_code: "YER",
    plug_type: "A,D,G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "257",
    country_name: "Zambia",
    country_code: "ZM",
    country_calling_code: "260",
    currency_name: "Zambian Kwacha",
    currency_code: "ZMW",
    plug_type: "C,D,G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
  {
    id: "258",
    country_name: "Zimbabwe",
    country_code: "ZW",
    country_calling_code: "263",
    currency_name: "United States Dollar",
    currency_code: "USD",
    plug_type: "D,G",
    voltage: "230 V",
    frequency: "50 Hz",
  },
];
