export const ROUTES = {
  GET_LIST_BRAND: "/api/brand/get-list",
  GET_LIST_BRAND_CARD: "/api/brand/get-list-card",
  GET_LIST_BRAND_BY_ALPHABET: "/api/brand/get-all-alphabet",
  GET_ONE_BRAND: "/api/brand/get-one/{id}",
  UPDATE_BRAND: "/api/brand/update/{id}",
  UPDATE_BRAND_PROFILE: "/api/brand/update-profile",
  UPDATE_BRAND_LOGO: "/api/brand/update-logo",
  GET_BRAND_STATUSES: "/api/brand/statuses",
  SEND_EMAIL_INVITE_BRAND: "/api/brand/invite/{id}",
  GET_LIST_ASSIGN_TEAM: "/api/team/get-list",
  ASSIGN_TEAM: "/api/team/assign/{brand_id}",
  GET_LIST_DESIGN_FIRM: "/api/design/get-list",
  GET_ONE_DESIGN_FIRM: "/api/design/get-one/{id}",
  UPDATE_DESIGN_FIRM: "/api/design/update/{id}",
  GET_DESIGN_STATUSES: "/api/design/statuses",
  GET_LIST_PROJECT: "/api/project/get-list",
  GET_ONE_PROJECT: "/api/project/get-one/{id}",
  GET_LIST_CATEGORY: "/api/category/get-list",
  EDIT_CATEGORY: "/api/category/update/{id}",
  GET_ONE_CATEGORY: "/api/category/get-one/{id}",
  DELETE_CATEGORY: "/api/category/delete/{id}",
  CREATE_CATEGORY: "/api/category/create",
  GET_LIST_BASIS_CONVERSION: "/api/basis-conversion/get-list",
  EDIT_BASIS_CONVERSION: "/api/basis-conversion/update/{id}",
  GET_ONE_BASIS_CONVERSION: "/api/basis-conversion/get-one/{id}",
  DELETE_BASIS_CONVERSION: "/api/basis-conversion/delete/{id}",
  CREATE_BASIS_CONVERSION: "/api/basis-conversion/create",
  GET_LIST_BASIS_OPTION: "/api/basis-option/get-list",
  EDIT_BASIS_OPTION: "/api/basis-option/update/{id}",
  GET_ONE_BASIS_OPTION: "/api/basis-option/get-one/{id}",
  DELETE_BASIS_OPTION: "/api/basis-option/delete/{id}",
  CREATE_BASIS_OPTION: "/api/basis-option/create",
  GET_LIST_BASIS_PRESET: "/api/basis-preset/get-list",
  EDIT_BASIS_PRESET: "/api/basis-preset/update/{id}",
  GET_ONE_BASIS_PRESET: "/api/basis-preset/get-one/{id}",
  DELETE_BASIS_PRESET: "/api/basis-preset/delete/{id}",
  CREATE_BASIS_PRESET: "/api/basis-preset/create",
  GET_LIST_ATTRIBUTE: "/api/attribute/get-list",
  GET_LIST_CONTENT_TYPE: "/api/attribute/content-type/get-list",
  EDIT_ATTRIBUTE: "/api/attribute/update/{id}",
  DELETE_ATTRIBUTE: "/api/attribute/delete/{id}",
  CREATE_ATTRIBUTE: "/api/attribute/create",
  GET_ONE_ATTRIBUTE: "/api/attribute/get-one/{id}",
  CREATE_PRODUCT: "/api/product/create",
  UPDATE_PRODUCT: "/api/product/update/{id}",
  DELETE_PRODUCT: "/api/product/delete/{id}",
  GET_LIST_PRODUCT: "/api/product/get-list",
  GET_ONE_PRODUCT: "/api/product/get-one/{id}",
  LIKE_OR_UNLIKE_PRODUCT: "/api/product/like/{id}",
  GET_BRAND_PRODUCT_SUMMARY: "/api/product/brand-product-summary/{brand_id}",
  GET_LIST_DOCUMENTATION: "/api/documentation/get-list",
  EDIT_DOCUMENTATION: "/api/documentation/update/{id}",
  DELETE_DOCUMENTATION: "/api/documentation/delete/{id}",
  CREATE_DOCUMENTATION: "/api/documentation/create",
  GET_ONE_DOCUMENTATION: "/api/documentation/get-one/{id}",
  GET_LIST_LOCATION: "/api/location/get-list",
  GET_LIST_LOCATION_WITH_GROUP: "/api/location/get-list-with-country-group",
  GET_ONE_LOCATION: "/api/location/get-one/{id}",
  EDIT_LOCATION: "/api/location/update/{id}",
  DELETE_LOCATION: "/api/location/delete/{id}",
  CREATE_LOCATION: "/api/location/create",
  GET_FUNCTIONAL_TYPES: "/api/functional-type/get-list",
  GET_DEPARTMENTS: "/api/department/get-list",

  GET_LIST_TEAM_PROFILE: "/api/team-profile/get-list",
  GET_ONE_TEAM_PROFILE: "/api/team-profile/get-one/{id}",
  GET_ME_TEAM_PROFILE: "/api/team-profile/get-me",
  UPDATE_ME_TEAM_PROFILE: "/api/team-profile/update-me",
  UPDATE_AVATAR_TEAM_PROFILE: "/api/team-profile/update-avatar",
  EDIT_TEAM_PROFILE: "/api/team-profile/update/{id}",
  DELETE_TEAM_PROFILE: "/api/team-profile/delete/{id}",
  CREATE_TEAM_PROFILE: "/api/team-profile/create",
  SEND_INVITE_TEAM_PROFILE: "/api/team-profile/invite/{id}",
  GET_LIST_PERMISSION: "/api/permission/get-list",
  OPEN_CLOSE_PERMISSION: "/api/permission/open-close/{id}",
  GET_LIST_EMAIL_AUTO: "/api/email-auto/get-list",
  GET_ONE_EMAIL_AUTO: "/api/email-auto/get-one/{id}",
  EDIT_EMAIL_AUTO: "/api/email-auto/update/{id}",
  DELETE_EMAIL_AUTO: "/api/email-auto/delete/{id}",
  CREATE_EMAIL_AUTO: "/api/email-auto/create",
  GET_LIST_QUOTATION: "/api/quotation/get-list",
  GET_ONE_QUOTATION: "/api/quotation/get-one/{id}",
  EDIT_QUOTATION: "/api/quotation/update/{id}",
  DELETE_QUOTATION: "/api/quotation/delete/{id}",
  CREATE_QUOTATION: "/api/quotation/create",
  GET_LIST_SERVICE: "/api/service/get-list",
  GET_ONE_SERVICE: "/api/service/get-one/{id}",
  CREATE_SERVICE: "/api/service/create",
  GET_LIST_SUBSCRIPTION: "/api/subscription/get-list",
  CREATE_CONTACT: "/api/contact/create",
  GET_LIST_CONTACT: "/api/contact/list",
  GET_ONE_CONTACT: "/api/contact/get-one/{id}",
  GET_ONE_SUBSCRIPTION: "/api/subscription/get-one/{id}",
  GET_LIST_COLLECTION: "/api/collection/get-list",
  CREATE_COLLECTION: "/api/collection/create",
  GET_LIST_REST_COLLECTION_PRODUCT:
    "/api/product/get-list-rest-collection-product/{id}",

  CREATE_PRODUCT_TIP: "/api/product-tip/create",
  GET_LIST_PRODUCT_TIP: "/api/product-tip/get-list",
  GET_ONE_PRODUCT_TIP: "/api/product-tip/get-one/{product_id}",
  EDIT_PRODUCT_TIP: "/api/product-tip/update/{product_id}",
  DELETE_PRODUCT_TIP: "/api/product-tip/delete/{product_id}",
  GET_LIST_PRODUCT_TIP_BY_PRODUCT_ID:
    "/api/product-tip/get-list-by-product/{id}",

  CREATE_PRODUCT_DOWNLOAD: "/api/product-download/create",
  GET_LIST_PRODUCT_DOWNLOAD: "/api/product-download/get-list",
  GET_ONE_PRODUCT_DOWNLOAD: "/api/product-download/get-one/{product_id}",
  EDIT_PRODUCT_DOWNLOAD: "/api/product-download/update/{product_id}",
  DELETE_PRODUCT_DOWNLOAD: "/api/product-download/delete/{product_id}",
  GET_LIST_PRODUCT_DOWNLOAD_BY_PRODUCT_ID:
    "/api/product-download/get-list-by-product/{id}",

  GET_LIST_AUTO_EMAIL_TOPIC: "/api/email-auto/get-list-topic",
  GET_LIST_AUTO_EMAIL_TARGETED_FOR: "/api/email-auto/get-list-targeted-for",

  GET_LIST_PROJECT_CARD: "/api/project/get-list-card",
  CREATE_PROJECT: "/api/project/create",
  UPDATE_PROJECT: "/api/project/update/{id}",
  DELETE_PROJECT: "/api/project/delete/{id}",
  CREATE_INQUIRY: "/api/inquiry/create",
  UPDATE_INQUIRY: "/api/inquiry/update/{id}",
  DELETE_INQUIRY: "/api/inquiry/delete/{id}",
  GET_LIST_INQUIRY: "/api/inquiry/get-list",
  GET_ONE_INQUIRY: "/api/inquiry/get-one/{id}",
  CREATE_DISTRIBUTOR: "/api/distributor/create",
  UPDATE_DISTRIBUTOR: "/api/distributor/update/{id}",
  DELETE_DISTRIBUTOR: "/api/distributor/delete/{id}",
  GET_LIST_DISTRIBUTOR: "/api/distributor/get-list",
  GET_ONE_DISTRIBUTOR: "/api/distributor/get-one/{id}",
  GET_MARKET_DISTRIBUTOR_COUNTRY_GROUP: "/api/distributor/market/{product_id}",
  CREATE_MARKET_AVAILABILITY: "/api/market-availability/create",
  UPDATE_MARKET_AVAILABILITY: "/api/market-availability/update/{id}",
  DELETE_MARKET_AVAILABILITY: "/api/market-availability/delete/{id}",
  GET_LIST_MARKET_AVAILABILITY: "/api/market-availability/get-list",
  GET_ONE_MARKET_AVAILABILITY: "/api/market-availability/get-one/{id}",
  UPDATE_DESIGN_PROFILE: "/api/design/update-profile",
  CREATE_PROJECT_ZONE: "/api/project-zone/create",
  UPDATE_PROJECT_ZONE: "/api/project-zone/update/{id}",
  DELETE_PROJECT_ZONE: "/api/project-zone/delete/{id}",
  GET_LIST_PROJECT_ZONE: "/api/project-zone/get-list",
  GET_ONE_PROJECT_ZONE: "/api/project-zone/get-one/{id}",
  CREATE_MATERIAL_CODE: "/api/material-code/create",
  UPDATE_MATERIAL_CODE: "/api/material-code/update/{id}",
  DELETE_MATERIAL_CODE: "/api/material-code/delete/{id}",
  GET_LIST_MATERIAL_CODE: "/api/material-code/get-list",
  GET_ONE_MATERIAL_CODE: "/api/material-code/get-one/{id}",
  GET_ALL_ATTRIBUTE: "/api/attribute/get-all",

  CREATE_PRODUCT_CATELOGUE_DOWNLOAD: "/api/product-catelogue-download/create",
  GET_LIST_PRODUCT_CATELOGUE_DOWNLOAD:
    "/api/product-catelogue-download/get-list",
  GET_ONE_PRODUCT_CATELOGUE_DOWNLOAD:
    "/api/product-catelogue-download/get-one/{product_id}",
  EDIT_PRODUCT_CATELOGUE_DOWNLOAD:
    "/api/product-catelogue-download/update/{product_id}",
  DELETE_PRODUCT_CATELOGUE_DOWNLOAD:
    "/api/product-catelogue-download/delete/{product_id}",

  GET_COUNTRY: "/api/location/get-country/{id}",
  GET_STATE: "/api/location/get-state/{id}",
  GET_CITY: "/api/location/get-city/{id}",

  CREATE_BRAND: "/api/brand/create",
  DUPLICATE_PRODUCT: "/api/product/duplicate/{id}",
  UPDATE_HOWTO: "/api/documentation/howto/update",
  GET_ALL_HOWTO: "/api/documentation/howto/get-all",
  GET_ALL_BRAND_SUMMARY: "/api/brand/summary",
  DELETE_COLLECTION: "/api/collection/delete/{id}",
  GET_LIST_DESIGNER_BRAND_PRODUCTS: "/api/product/design/get-list",
  GET_PROJECT_TYPES: "/api/project/project-types",
  GET_BUILDING_TYPES: "/api/project/building-types",
  GET_PRODUCT_OPTIONS: "/api/product/{id}/attribute/{attribute_id}/get-options",
  ASSIGN_PRODUCT_TO_PROJECT: "/api/product/assign",
  SHARE_PRODUCT_BY_EMAIL: "/api/product/share-via-email",
  GET_SHARING_GROUPS: "/api/product/sharing-groups",
  GET_SHARING_PURPOSES: "/api/product/sharing-purposes",

  GET_PROJECT_SUMMARY: "/api/project/get-summary",
  GET_PROJECT_SUMMARY_OVERALL: "/api/project/get-summary-overall",
  GET_PROJECT_LISTING: "/api/project/listing",
  GET_MARKET_LOCATIONS_COUNTRY_GROUP: "/api/location/market/{product_id}",
  GET_BRAND_LOCATIONS_COUNTRY_GROUP: "/api/location/brand/{brand_id}",
  GET_CONSIDERED_PRODUCTS: "/api/considered-product/get-list/{project_id}",
  GET_CONSIDERED_PRODUCT_STATUS: "/api/considered-product/status",
  GET_BRAND_TEAM_GROUP_BY_COUNTRY: "/api/team-profile/brand/{brand_id}",
  SPECIFY_PRODUCT: "/api/specified-product/specify",
  GET_REQUIREMENT_TYPES: "/api/requirement-type/get-list",
  GET_INSTRUCTION_TYPES: "/api/instruction-type/get-list",
  GET_UNIT_TYPES: "/api/unit-type/get-list",
  GET_ONE_SPECIFIED_PRODUCT:
    "/api/specified-product/get-one/{considered_product_id}",
  GET_DESIGN_LOCATIONS_COUNTRY_GROUP: "/api/location/design/{design_id}",
  GET_DESIGN_TEAM_GROUP_BY_COUNTRY: "/api/team-profile/design/{design_id}",
  GET_ALL_DESIGN_FIRM_SUMMARY: "/api/design/summary",
  GET_SPECIFIED_PRODUCTS_BY_BRAND:
    "/api/specified-product/get-list-brand/{project_id}",
  GET_SPECIFIED_PRODUCTS_BY_MATERIAL:
    "/api/specified-product/get-list-material/{project_id}",
  GET_SPECIFIED_PRODUCTS_BY_ZONE:
    "/api/specified-product/get-list-zone/{project_id}",
  GET_MARKET_AVAILABILITY_GROUP_BY_COLLECTION:
    "/api/market-availability/get-list-group-by-collection/{brand_id}",
  GET_PROJECT_GROUP_BY_STATUS: "/api/project/get-list-group-by-status",
  GET_DISTRIBUTOR_GROUP_BY_COUNTRY:
    "/api/distributor/get-list-group-by-country",
  GET_ALL_PROJECT: "/api/project/get-all",
  GET_MATERIAL_CODE_GROUP: "/api/material-code/get-list-group/{design_id}",
  UPDATE_DESIGN_STATUS: "/api/design/update-status/{id}",
  UPDATE_BRAND_STATUS: "/api/brand/update-status/{id}",
  GET_LIST_ASSIGNED_PROJECT:
    "/api/considered-product/get-list-assigned/{project_id}/{product_id}",
  GET_TISC_TEAM_PROFILE: "/api/team/get-list-group-team-profile/{brand_id}",
  UPDATE_STATUS_CONSIDER_PRODUCT: "/api/considered-product/update-status/{id}",
  DELETE_CONSIDER_PRODUCT: "/api/considered-product/delete/{id}",
  GET_LIST_POLICY_LANDING_PAGE: "/api/documentation/get-list-policy",
  FAVOURITE: {
    SKIP: "/api/favourite/skip",
    RETRIEVE: "/api/favourite/retrieve",
    LIST: "/api/favourite/product-list",
    SUMMARY: "/api/favourite/product-summary",
  },
  UPDATE_PRODUCT_SPECIFIED_STATUS: "/api/specified-product/update-status/{id}",
  DELETE_PRODUCT_SPECIFIED_STATUS: "/api/specified-product/delete/{id}",
  GET_LIST_QUOTATION_NOT_AUTH: "/api/quotation/landing-page/get-list",
  SETTING: {
    COUNTRY_REGION_GROUP: "/api/setting/regions",
    COMMON_TYPES_LIST: "/api/setting/common-type/{type}",
    GET_COUNTRIES: "/api/setting/countries",
    GET_STATES: "/api/setting/states",
    GET_CITIES: "/api/setting/cities",
    FIND_COUNTRY: "/api/setting/countries/{id}",
    FIND_STATE: "/api/setting/states/{id}",
    FIND_CITY: "/api/setting/cities/{id}",
    GET_MEASUREMENT_UNIT: "/api/setting/measurement-units",
    GET_FUNCTIONAL_TYPE: "/api/setting/functional-type",
  },
  MATERIAL_CODE: {
    GET_MATERIAL_CODES: "/api/material-code/get-list",
    UPDATE_MATERIAL_CODE: "/api/material-code/update/{id}",
    DELETE_MATERIAL_CODE: "/api/material-code/delete/{id}",
    CREATE_MATERIAL_CODE: "/api/material-code/create",
    GET_MATERIAL_CODE: "/api/material-code/get-one/{id}",
    GET_LIST_CODE_MATERIAL_CODE: "/api/material-code/get-list-code",
  },
  ASSIGN_TEAM_PROJECT: "/api/project/{id}/assign-team",
  GENERAL_INQUIRY: {
    CREATE: "/api/general-inquiry",
    GET_LIST: "/api/general-inquiry",
    SUMMARY: "/api/general-inquiry/summary",
    GET_ONE: "/api/general-inquiry/{id}",
  },
  ACTION_TASK: {
    CREATE: "/api/action-task",
    GET_LIST: "/api/action-task",
    UPDATE: "/api/action-task/{id}",
  },
  DESIGN_FIRM: {
    UPDATE_DESIGN_FIRM: "/api/design/office-profile/{id}",
    GET_LIST_DESIGN_FIRM: "/api/design/get-list",
    GET_ONE_DESIGN_FIRM: "/api/design/get-one/{id}",
    GET_DESIGN_STATUSES: "/api/design/statuses",
    GET_ALL_DESIGN_FIRM_SUMMARY: "/api/design/summary",
    UPDATE_DESIGN_STATUS: "/api/design/update-status/{id}",
  },
  PROJECT_PRODUCT: {
    ASSIGN_PRODUCT_TO_A_PROJECT: "/api/project/assign-product",
    GET_PROJECT_ASSIGN_ZONE_BY_PRODUCT:
      "/api/project/{project_id}/product/{product_id}/assign-zones",
    GET_CONSIDERED_PRODUCT_LIST:
      "/api/project/{project_id}/considered-product/get-list",
    DELETE_CONSIDERED_PRODUCT: "/api/project-product/{id}/delete",
    UPDATE_CONSIDERED_PRODUCT_STATUS:
      "/api/project-product/{id}/update-consider-status",
    UPDATE_SPECIFIED_PRODUCT_STATUS:
      "/api/project-product/{id}/update-specified-status",
    UPDATE_CONSIDERED_PRODUCT_SPECIFY:
      "/api/project-product/{id}/update-specify",
    GET_SPECIFYING_PRODUCTS_BY_BRAND:
      "/api/project-product/get-list-by-brand/{project_id}",
    GET_SPECIFYING_PRODUCTS_BY_MATERIAL:
      "/api/project-product/get-list-by-material/{project_id}",
    GET_SPECIFYING_PRODUCTS_BY_ZONE:
      "/api/project-product/get-list-by-zone/{project_id}",
    GET_LIST_FINISH_SCHEDULE_FOR:
      "/api/project-product/{project_product_id}/finish-schedules",
  },
  PROJECT_TRACKING: {
    CREATE: "/api/project-tracking/request/create",
    GET_LIST: "/api/project-tracking/get-list",
    GET_ONE: "/api/project-tracking/{id}/get-one",
    UPDATE: "/api/project-tracking/{id}/update",
    GET_SUMMARY: "/api/project-tracking/summary",
  },
  PDF: {
    GENERATE_PROJECT_PDF: "/api/pdf/project/{project_id}/generate",
    GET_PROJECT_PDF_CONFIG: "/api/pdf/project/config/{project_id}",
  },
  PRE_SPECFICATION: {
    GET_USER_SPEC_SELECTION: "/api/product/{id}/select-specification/get-list",
    UPDATE_USER_SPEC_SELECTION: "/api/product/{id}/select-specification/update",
  },
};
