const uuid = require("uuid").v4;
const moment = require("moment");

const { COMMON_TYPES } = require("./constant");
const COMMON_TYPES_ATTRIBUTES = require("./constant").COMMON_TYPES_ATTRIBUTES;

const seed = async (db) => {
  const commonTypeCollection = await db.collection("common_types");
  const createAndSeed = async (collection) => {
    await collection.create();
    await collection.get();
    const records = [
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        name: "Architects/Interior Designers",
        general_type: COMMON_TYPES.SHARING_GROUP,
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        name: "Builders/Contractors",
        general_type: COMMON_TYPES.SHARING_GROUP,
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        name: "Clients/Customers",
        general_type: COMMON_TYPES.SHARING_GROUP,
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        name: "Distributors/Sales Agents",
        general_type: COMMON_TYPES.SHARING_GROUP,
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        name: "Internal Team Members",
        general_type: COMMON_TYPES.SHARING_GROUP,
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        name: "Other Professional Consultants",
        general_type: COMMON_TYPES.SHARING_GROUP,
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        name: "Approval/Confirmation",
        general_type: COMMON_TYPES.SHARING_PURPOSE,
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        name: "Comment/Feedback",
        general_type: COMMON_TYPES.SHARING_PURPOSE,
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        name: "General Review/Sharing",
        general_type: COMMON_TYPES.SHARING_PURPOSE,
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        name: "Internal Evaluation/Discussion",
        general_type: COMMON_TYPES.SHARING_PURPOSE,
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        name: "Project Proposal/Submission",
        general_type: COMMON_TYPES.SHARING_PURPOSE,
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        name: "Recommendation/Suggestion",
        general_type: COMMON_TYPES.SHARING_PURPOSE,
        created_at: moment(),
      },

      // finish schedule
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.FINISH_SCHEDULES,
        name: "Base @ Celling + Floor",
        created_at: moment(),
        design_id: "",
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.FINISH_SCHEDULES,
        name: "Base @ Celling",
        created_at: moment(),
        design_id: "",
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.FINISH_SCHEDULES,
        name: "Base @ Floor",
        created_at: moment(),
        design_id: "",
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.FINISH_SCHEDULES,
        name: "Cabinet Carcass + Door",
        created_at: moment(),
        design_id: "",
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.FINISH_SCHEDULES,
        name: "Cabinet Carcass",
        created_at: moment(),
        design_id: "",
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.FINISH_SCHEDULES,
        name: "Cabinet Door",
        created_at: moment(),
        design_id: "",
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.FINISH_SCHEDULES,
        name: "Celling Surface",
        created_at: moment(),
        design_id: "",
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.FINISH_SCHEDULES,
        name: "Door Frame + Door Panel",
        created_at: moment(),
        design_id: "",
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.FINISH_SCHEDULES,
        name: "Door Frame",
        created_at: moment(),
        design_id: "",
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.FINISH_SCHEDULES,
        name: "Door Panel",
        created_at: moment(),
        design_id: "",
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.FINISH_SCHEDULES,
        name: "Floor Surface",
        created_at: moment(),
        design_id: "",
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.FINISH_SCHEDULES,
        name: "Wall Surface",
        created_at: moment(),
        design_id: "",
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.FINISH_SCHEDULES,
        name: "Wall-East",
        created_at: moment(),
        design_id: "",
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.FINISH_SCHEDULES,
        name: "Wall-South",
        created_at: moment(),
        design_id: "",
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.FINISH_SCHEDULES,
        name: "Wall-West",
        created_at: moment(),
        design_id: "",
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.FINISH_SCHEDULES,
        name: "Wall-North",
        created_at: moment(),
        design_id: "",
      },

      //functional type
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.COMPANY_FUNCTIONAL,
        name: "Business Office",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.COMPANY_FUNCTIONAL,
        name: "Headquarter",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.COMPANY_FUNCTIONAL,
        name: "Regional Office",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.COMPANY_FUNCTIONAL,
        name: "Local Office",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.COMPANY_FUNCTIONAL,
        name: "Experience Center",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.COMPANY_FUNCTIONAL,
        name: "Showroom & Gallery",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.COMPANY_FUNCTIONAL,
        name: "Customer & Service Center",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.COMPANY_FUNCTIONAL,
        name: "Factory & Fabrication Shop",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.COMPANY_FUNCTIONAL,
        name: "Logistic Facility & Warehouse",
        created_at: moment(),
      },

      //building type
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_BUILDING,
        name: "Addition & Alteration",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_BUILDING,
        name: "Concept & Competition",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_BUILDING,
        name: "Conversation & Restoration",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_BUILDING,
        name: "Iterior Fit-out & Renovation",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_BUILDING,
        name: "Landscaping & Outdoorm Space",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_BUILDING,
        name: "Master & Urban Planning",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_BUILDING,
        name: "New Building & Construction",
        created_at: moment(),
      },

      //instruction type
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_INSTRUCTION,
        name: "Image included for reference only",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_INSTRUCTION,
        name: "Refer to control sample for actual finish",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_INSTRUCTION,
        name: "Product conforms to code and regulation",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_INSTRUCTION,
        name: "Product conforms to industry standards",
        created_at: moment(),
      },

      //project type
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_TYPE,
        name: "Airport, Station, Transportation Hub",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_TYPE,
        name: "Apartment, Condo, Multi-unit Housing",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_TYPE,
        name: "Arena, Sports Hall, Stadium",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_TYPE,
        name: "Bank Building, High-Security Facility",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_TYPE,
        name: "Club, Entertainment, Gaming Complex",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_TYPE,
        name: "Cultural Space, Gallery, Museum",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_TYPE,
        name: "Commerce, Retail Store, Shopping Mall",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_TYPE,
        name: "Data Center, IT Facility",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_TYPE,
        name: "Distribution Center, Factory, Warehouse",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_TYPE,
        name: "Educational Space, Library, School",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_TYPE,
        name: "Food & Beverage, Hospitality Outlet",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_TYPE,
        name: "Government, Institutional Building",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_TYPE,
        name: "Healthcare, Hospital, Medical Facility",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_TYPE,
        name: "Hotel, Resort, Motel, Lodging Facility",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_TYPE,
        name: "Landscaping, Park, Playground",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_TYPE,
        name: "Meetings, Incentives, Conferences, Exhibitions",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_TYPE,
        name: "Mixed-Use Development",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_TYPE,
        name: "Office Building, Workplace Space",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_TYPE,
        name: "Prison, Confinement Facility",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_TYPE,
        name: "Public Space, Monument, Open Plaza",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_TYPE,
        name: "Religion Building, Worship Facility",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_TYPE,
        name: "Single House, Private Residence",
        created_at: moment(),
      },

      // requirement type
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_REQUIREMENT,
        name: "Cutting",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_REQUIREMENT,
        name: "Finishing Sample",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_REQUIREMENT,
        name: "Flame Certificate",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_REQUIREMENT,
        name: "LEED Certificate",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_REQUIREMENT,
        name: "Prototype",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_REQUIREMENT,
        name: "Seaming Diagram",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_REQUIREMENT,
        name: "Shop Drawings",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_REQUIREMENT,
        name: "Strike-off",
        created_at: moment(),
      },

      //unit type
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Not Applicable",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Average",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Bag",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Bale",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Band",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Bar",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Barrel",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Bin",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Block",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Board Feet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Bolt",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Bottle",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Box",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Bowl",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Bucket",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Bulk",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Bundle",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Can",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Capsule",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Card",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Carton",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Cartridge",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Case",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Cassette",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Centimeter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Coil",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Container",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Cord",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Count",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Crate",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Cubic Centimeter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Cubic Feet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Cubic Inche",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Cubic Meter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Cubic Yard",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Cup",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Cylinder",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Diameter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Display",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Dozen",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Drum",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Each",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Feet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Gallon",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Gauge",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Grain",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Gram",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Gross",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Hank",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Inch",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Jar",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Jug",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Keg",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Kilogram",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Kit",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Length",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Linear Centimeter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Linear Foot",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Linear Meter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Linear Yard",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Link",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Liter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Lot",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Meter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Order",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Ounce",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Pack",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Package",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Packet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Pad",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Page",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Pail",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Pair",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Pallet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Piece",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Pint",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Plate",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Pound",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Quart",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Quarter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Rack",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Ream",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Reel",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Rod",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Roll",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Sachet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Sack",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Set",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Sheet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Single",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Sleeve",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Spool",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Square Foot",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Square Meter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Square Yard",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Stack",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Tablet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Tank",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Tray",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Ton",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Tub",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Tube",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Unit",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Vial",
        design_id: "",
        created_at: moment(),
      },
      {
        ...COMMON_TYPES_ATTRIBUTES,
        id: uuid(),
        general_type: COMMON_TYPES.PROJECT_UNIT,
        name: "Yard",
        design_id: "",
        created_at: moment(),
      },
    ];

    records.forEach(async (record) => {
      await db.query({
        query: `insert ${JSON.stringify(record)} into @@model`,
        bindVars: {
          "@model": "common_types",
        },
      });
    });
    console.log("success seed common type data");
  };
  try {
    await createAndSeed(commonTypeCollection);
  } catch (error) {
    if (error.message === "duplicate name") {
      await commonTypeCollection.drop();
      await createAndSeed(commonTypeCollection);
    }
  }
};

module.exports = {
  seed,
};
