const SYSTEM_TYPE = {
  TISC: 1,
  BRAND: 2,
  DESIGN: 3,
};
const ROLES = {
  TISC_ADMIN: "4fb9a23d-d60a-45a4-8ed4-2300276bc19b",
  TISC_CONSULTANT_TEAM: "248a21fc-42e0-48c6-9bc2-b95e11a81fb7",
  BRAND_ADMIN: "62ad5077-6183-435e-97f8-81c35065504e",
  BRAND_TEAM: "c93584c7-7987-4be0-aa7d-e48e20960630",
  DESIGN_ADMIN: "68fdf6d0-464e-404b-90e8-5d02a48ac498",
  DESIGN_TEAM: "1493b47a-1118-43e2-9bd8-1a3c3adc3f13",
};
const PERMISSION_TITLE = {
  MY_WORKSPACE: "MY WORKSPACE",
  USER_GROUP: "USER GROUP",
  USER_GROUP_BRAND: "Brands",
  USER_GROUP_DESIGN: "Design Firms",
  PROJECT: "PROJECTS",
  PROJECT_LIST: "Listing",
  PRODUCT: "PRODUCTS",
  PRODUCT_CATEGORY: "Categories",
  PRODUCT_BASIS: "Basis",
  PRODUCT_ATTRIBUTE: "Attributes",
  PRODUCT_CONFIGURATION: "Configurations",
  ADMINISTRATION: "ADMINISTRATION",
  ADMINISTRATION_DOCUMENTATION: "Documentations",
  ADMINISTRATION_LOCATION: "Locations",
  ADMINISTRATION_TEAM_PROFILE: "Team profiles",
  ADMINISTRATION_MESSAGE: "Messages",
  ADMINISTRATION_REVENUE: "Revenues",
};
const ROUTES = {
  GET_LIST_WORKSPACE: "/api/work-space",
  GET_LIST_BRAND: "/api/brand/get-list",
  GET_LIST_BRAND_BY_ALPHABET: "/api/brand/get-all-alphabet",
  GET_ONE_BRAND: "/api/brand/get-one/{id}",
  UPDATE_BRAND: "/api/brand/update/{id}",
  SEND_EMAIL_INVITE_BRAND: "/api/brand/invite/{id}",
  GET_LIST_ASSIGN_TEAM: "/api/team/get-list",
  ASSIGN_TEAM: "/api/team/assign/{id}",
  GET_LIST_DESIGN_FIRM: "/api/design/get-list",
  GET_ONE_DESIGN_FIRM: "/api/design/get-one/{id}",
  UPDATE_DESIGN_FIRM: "/api/design/update/{id}",
  GET_LIST_PROJECT: "/api/project/get-list",
  GET_ONE_PROJECT: "/api/project/get-one/{id}",
  GET_LIST_CATEGORY: "/api/category/get-list",
  EDIT_CATEGORY: "/api/category/update/{id}",
  GET_ONE_CATEGORY: "/api/category/get-one/{id}",
  DELETE_CATEGORY: "/api/category/delete/{id}",
  CREATE_CATEGORY: "/api/category/create",
  GET_LIST_BASIS_CONVERSION: "/api/basis-conversion/get-list",
  EDIT_BASIS_CONVERSION: "/api/basis-conversion/update/{id}",
  GET_ONE_BASIS_CONVERSION: "/api/basis-conversion/get-one/{id}",
  DELETE_BASIS_CONVERSION: "/api/basis-conversion/delete/{id}",
  CREATE_BASIS_CONVERSION: "/api/basis-conversion/create",
  GET_LIST_BASIS_OPTION: "/api/basis-option/get-list",
  EDIT_BASIS_OPTION: "/api/basis-option/update/{id}",
  GET_ONE_BASIS_OPTION: "/api/basis-option/get-one/{id}",
  DELETE_BASIS_OPTION: "/api/basis-option/delete/{id}",
  CREATE_BASIS_OPTION: "/api/basis-option/create",
  GET_LIST_BASIS_PRESET: "/api/basis-preset/get-list",
  EDIT_BASIS_PRESET: "/api/basis-preset/update/{id}",
  GET_ONE_BASIS_PRESET: "/api/basis-preset/get-one/{id}",
  DELETE_BASIS_PRESET: "/api/basis-preset/delete/{id}",
  CREATE_BASIS_PRESET: "/api/basis-preset/create",
  GET_LIST_ATTRIBUTE: "/api/attribute/get-list",
  GET_LIST_CONTENT_TYPE: "/api/attribute/content-type/get-list",
  EDIT_ATTRIBUTE: "/api/attribute/update/{id}",
  DELETE_ATTRIBUTE: "/api/attribute/delete/{id}",
  CREATE_ATTRIBUTE: "/api/attribute/create",
  GET_ONE_ATTRIBUTE: "/api/attribute/get-one/{id}",
  CREATE_PRODUCT: "/api/product/create",
  UPDATE_PRODUCT: "/api/product/update/{id}",
  GET_LIST_PRODUCT: "/api/product/get-list",
  GET_ONE_PRODUCT: "/api/product/get-one/{id}",
  GET_LIST_DOCUMENTATION: "/api/documentation/get-list",
  EDIT_DOCUMENTATION: "/api/documentation/update/{id}",
  DELETE_DOCUMENTATION: "/api/documentation/delete/{id}",
  CREATE_DOCUMENTATION: "/api/documentation/create",
  GET_ONE_DOCUMENTATION: "/api/documentation/get-one/{id}",
  GET_LIST_LOCATION: "/api/location/get-list",
  GET_ONE_LOCATION: "/api/location/get-one/{id}",
  EDIT_LOCATION: "/api/location/update/{id}",
  DELETE_LOCATION: "/api/location/delete/{id}",
  CREATE_LOCATION: "/api/location/create",
  GET_LIST_TEAM_PROFILE: "/api/team-profile/get-list",
  GET_ONE_TEAM_PROFILE: "/api/team-profile/get-one/{id}",
  GET_ME_TEAM_PROFILE: "/api/team-profile/get-me",
  UPDATE_ME_TEAM_PROFILE: "/api/team-profile/update-me",
  UPDATE_AVATAR_TEAM_PROFILE: "/api/team-profile/update-avatar",
  EDIT_TEAM_PROFILE: "/api/team-profile/update/{id}",
  DELETE_TEAM_PROFILE: "/api/team-profile/delete/{id}",
  CREATE_TEAM_PROFILE: "/api/team-profile/create",
  SEND_INVITE_TEAM_PROFILE: "/api/team-profile/invite/{id}",
  GET_LIST_PERMISSION: "/api/permission/get-list",
  OPEN_CLOSE_PERMISSION: "/api/permission/open-close/{id}",
  GET_LIST_EMAIL_AUTO: "/api/email-auto/get-list",
  GET_ONE_EMAIL_AUTO: "/api/email-auto/get-one/{id}",
  EDIT_EMAIL_AUTO: "/api/email-auto/update/{id}",
  DELETE_EMAIL_AUTO: "/api/email-auto/delete/{id}",
  CREATE_EMAIL_AUTO: "/api/email-auto/create",
  GET_LIST_QUOTATION: "/api/quotation/get-list",
  GET_ONE_QUOTATION: "/api/quotation/get-one/{id}",
  EDIT_QUOTATION: "/api/quotation/update/{id}",
  DELETE_QUOTATION: "/api/quotation/delete/{id}",
  CREATE_QUOTATION: "/api/quotation/create",
  GET_LIST_SERVICE: "/api/service/get-list",
  GET_ONE_SERVICE: "/api/service/get-one/{id}",
  CREATE_SERVICE: "/api/service/create",
  GET_LIST_SUBSCRIPTION: "/api/subscription/get-list",
  CREATE_CONTACT: "/api/contact/create",
  GET_LIST_CONTACT: "/api/contact/list",
  GET_ONE_CONTACT: "/api/contact/get-one/{id}",
  GET_ONE_SUBSCRIPTION: "/api/subscription/get-one/{id}",
  GET_LIST_COLLECTION: "/api/collection/get-list",
  CREATE_COLLECTION: "/api/collection/create",
};
const USER_STATUSES = {
  ACTIVE: 1,
  BLOCKED: 0,
  PENDING: 2,
};
const USER_NULL_ATTRIBUTES = {
  id: null,
  role_id: null,
  firstname: null,
  lastname: null,
  gender: null,
  location_id: null,
  department: null,
  position: null,
  email: null,
  phone: null,
  mobile: null,
  password: null,
  avatar: null,
  backup_email: null,
  personal_mobile: null,
  linkedin: null,
  is_verified: null,
  verification_token: null,
  reset_password_token: null,
  status: null,
  created_at: null,
  type: null,
  relation_id: null,
  is_deleted: false,
};
const BRAND_NULL_ATTRIBUTES = {
  id: null,
  name: null,
  parent_company: null,
  logo: null,
  slogan: null,
  mission_n_vision: null,
  offical_websites: null,
  team_profile_ids: null,
  location_ids: null,
  status: null,
  created_at: null,
  updated_at: null,
  is_deleted: false,
};
const BRAND_STATUSES = {
  ACTIVE: 0,
  INACTIVE: 1,
  PENDING: 2,
};
const DESIGN_NULL_ATTRIBUTES = {
  id: null,
  name: null,
  parent_company: null,
  logo: null,
  slogan: null,
  profile_n_philosophy: null,
  offical_website: null,
  design_capabilities: null,
  team_profile_ids: null,
  location_ids: null,
  material_code_ids: null,
  project_ids: null,
  status: null,
  created_at: null,
  updated_at: null,
  is_deleted: false,
};
const DESIGN_STATUSES = {
  ACTIVE: 0,
  INACTIVE: 1,
};
const CATEGORY_NULL_ATTRIBUTES = {
  id: null,
  name: null,
  subs: null,
  created_at: null,
  is_deleted: false,
};
module.exports = {
  ROLES,
  PERMISSION_TITLE,
  ROUTES,
  SYSTEM_TYPE,
  USER_STATUSES,
  USER_NULL_ATTRIBUTES,
  BRAND_NULL_ATTRIBUTES,
  BRAND_STATUSES,
  DESIGN_NULL_ATTRIBUTES,
  DESIGN_STATUSES,
  CATEGORY_NULL_ATTRIBUTES,
};
