const SYSTEM_TYPE = {
  TISC: 1,
  BRAND: 2,
  DESIGNER: 3,
};
const ROLES = {
  TISC_ADMIN: "4fb9a23d-d60a-45a4-8ed4-2300276bc19b",
  TISC_CONSULTANT_TEAM: "248a21fc-42e0-48c6-9bc2-b95e11a81fb7",
  BRAND_ADMIN: "62ad5077-6183-435e-97f8-81c35065504e",
  BRAND_TEAM: "c93584c7-7987-4be0-aa7d-e48e20960630",
  DESIGNER_ADMIN: "68fdf6d0-464e-404b-90e8-5d02a48ac498",
  DESIGNER_TEAM: "1493b47a-1118-43e2-9bd8-1a3c3adc3f13",
};
const PERMISSION_TITLE = {
  MY_WORKSPACE: "MY WORKSPACE",
  USER_GROUP: "USER GROUP",
  USER_GROUP_BRAND: "brands",
  USER_GROUP_DESIGN: "design firms",
  PROJECT: "PROJECTS",
  PROJECT_LIST: "listing",
  PRODUCT: "PRODUCTS",
  PRODUCT_CATEGORY: "categories",
  PRODUCT_BASIS: "basis",
  PRODUCT_ATTRIBUTE: "attributes",
  PRODUCT_CONFIGURATION: "configurations",
  ADMINISTRATION: "ADMINISTRATION",
  ADMINISTRATION_DOCUMENTATION: "documentations",
  ADMINISTRATION_LOCATION: "locations",
  ADMINISTRATION_TEAM_PROFILE: "team profiles",
  ADMINISTRATION_MESSAGE: "messages",
  ADMINISTRATION_REVENUE: "revenues",
};
const ROUTES = {
  GET_LIST_WORKSPACE: "/api/work-space",
  GET_LIST_BRAND: "/api/brand/get-list",
  GET_ONE_BRAND: "/api/brand/get-one/{id}",
  UPDATE_BRAND: "/api/brand/update/{id}",
  SEND_EMAIL_INVITE_BRAND: "/api/brand/invite/{id}",
  GET_LIST_ASSIGN_TEAM: "/api/team/get-list",
  ASSIGN_TEAM: "/api/team/assign/{id}",
  GET_LIST_DESIGN_FIRM: "/api/design/get-list",
  GET_ONE_DESIGN_FIRM: "/api/design/get-one",
  UPDATE_DESIGN_FIRM: "/api/design/update/{id}",
  GET_LIST_PROJECT: "/api/project/get-list",
  GET_ONE_PROJECT: "/api/project/get-one",
  GET_LIST_CATEGORY: "/api/category/get-list",
  EDIT_CATEGORY: "/api/category/update/{id}",
  DELETE_CATEGORY: "/api/category/delete/{id}",
  CREATE_CATEGORY: "/api/category/create",
  GET_LIST_BASIS: "/api/basis/get-list",
  EDIT_BASIS: "/api/basis/update/{id}",
  DELETE_BASIS: "/api/basis/delete/{id}",
  CREATE_BASIS: "/api/basis/create",
  GET_LIST_ATTRIBUTE: "/api/attribute/get-list",
  EDIT_ATTRIBUTE: "/api/attribute/update/{id}",
  DELETE_ATTRIBUTE: "/api/attribute/delete/{id}",
  CREATE_ATTRIBUTE: "/api/attribute/create",
  CREATE_PRODUCT: "/api/product/create",
  GET_LIST_DOCUMENTATION: "/api/documentation/get-list",
  EDIT_DOCUMENTATION: "/api/documentation/update/{id}",
  DELETE_DOCUMENTATION: "/api/documentation/delete/{id}",
  CREATE_DOCUMENTATION: "/api/documentation/create",
  GET_LIST_LOCATION: "/api/location/get-list",
  GET_ONE_LOCATION: "/api/location/get-one",
  EDIT_LOCATION: "/api/location/update/{id}",
  DELETE_LOCATION: "/api/location/delete/{id}",
  CREATE_LOCATION: "/api/location/create",
  GET_LIST_TEAM_PROFILE: "/api/team-profile/get-list",
  GET_ONE_TEAM_PROFILE: "/api/team-profile/get-one",
  EDIT_TEAM_PROFILE: "/api/team-profile/update/{id}",
  DELETE_TEAM_PROFILE: "/api/team-profile/delete/{id}",
  CREATE_TEAM_PROFILE: "/api/team-profile/create",
  SEND_INVITE_TEAM_PROFILE: "/api/team-profile/invite/{id}",
  GET_LIST_PERMISSION: "/api/permission/get-list",
  GET_LIST_EMAIL_AUTO: "/api/email-auto/get-list",
  GET_ONE_EMAIL_AUTO: "/api/email-auto/get-one",
  EDIT_EMAIL_AUTO: "/api/email-auto/update/{id}",
  DELETE_EMAIL_AUTO: "/api/email-auto/delete/{id}",
  CREATE_EMAIL_AUTO: "/api/email-auto/create",
  GET_LIST_QUOTATION: "/api/quotation/get-list",
  GET_ONE_QUOTATION: "/api/quotation/get-one",
  EDIT_QUOTATION: "/api/quotation/update/{id}",
  DELETE_QUOTATION: "/api/quotation/delete/{id}",
  CREATE_QUOTATION: "/api/quotation/create",
  GET_LIST_SERVICE: "/api/service/get-list",
  GET_ONE_SERVICE: "/api/service/get-one",
  CREATE_SERVICE: "/api/service/create",
  GET_LIST_SUBSCRIPTION: "/api/subscription/get-list",
  GET_ONE_SUBSCRIPTION: "/api/subscription/get-one",
};
const USER_STATUSES = {
  ACTIVE: 1,
  BLOCKED: 0,
  PENDING: 2,
};
module.exports = {
  ROLES,
  PERMISSION_TITLE,
  ROUTES,
  SYSTEM_TYPE,
  USER_STATUSES,
};
