const SYSTEM_TYPE = {
  TISC: 1,
  BRAND: 2,
  DESIGN: 3,
};
const ROLES = {
  TISC_ADMIN: "4fb9a23d-d60a-45a4-8ed4-2300276bc19b",
  TISC_CONSULTANT_TEAM: "248a21fc-42e0-48c6-9bc2-b95e11a81fb7",
  BRAND_ADMIN: "62ad5077-6183-435e-97f8-81c35065504e",
  BRAND_TEAM: "c93584c7-7987-4be0-aa7d-e48e20960630",
  DESIGN_ADMIN: "68fdf6d0-464e-404b-90e8-5d02a48ac498",
  DESIGN_TEAM: "1493b47a-1118-43e2-9bd8-1a3c3adc3f13",
};
const PERMISSION_TITLE = {
  MY_WORKSPACE: "MY WORKSPACE",
  USER_GROUP: "USER GROUP",
  USER_GROUP_BRAND: "Brands",
  USER_GROUP_DESIGN: "Design Firms",
  PROJECT: "PROJECTS",
  PROJECT_LIST: "Listing",
  PRODUCT: "PRODUCTS",
  PRODUCT_CATEGORY: "Categories",
  PRODUCT_BASIS: "Basis",
  PRODUCT_ATTRIBUTE: "Attributes",
  PRODUCT_CONFIGURATION: "Configurations",
  ADMINISTRATION: "ADMINISTRATION",
  ADMINISTRATION_DOCUMENTATION: "Documentations",
  ADMINISTRATION_LOCATION: "Locations",
  ADMINISTRATION_TEAM_PROFILE: "Team profiles",
  ADMINISTRATION_MESSAGE: "Messages",
  ADMINISTRATION_REVENUE: "Revenues",
};
const ROUTES = {
  GET_LIST_BRAND: "/api/brand/get-list",
  GET_LIST_BRAND_CARD: "/api/brand/get-list-card",
  GET_LIST_BRAND_BY_ALPHABET: "/api/brand/get-all-alphabet",
  GET_ONE_BRAND: "/api/brand/get-one/{id}",
  UPDATE_BRAND: "/api/brand/update/{id}",
  UPDATE_BRAND_PROFILE: "/api/brand/update-profile",
  UPDATE_BRAND_LOGO: "/api/brand/update-logo",
  GET_BRAND_STATUSES: "/api/brand/statuses",
  SEND_EMAIL_INVITE_BRAND: "/api/brand/invite/{id}",
  GET_LIST_ASSIGN_TEAM: "/api/team/get-list",
  ASSIGN_TEAM: "/api/team/assign/{id}",
  GET_LIST_DESIGN_FIRM: "/api/design/get-list",
  GET_ONE_DESIGN_FIRM: "/api/design/get-one/{id}",
  UPDATE_DESIGN_FIRM: "/api/design/update/{id}",
  GET_DESIGN_STATUSES: "/api/design/statuses",
  GET_LIST_PROJECT: "/api/project/get-list",
  GET_ONE_PROJECT: "/api/project/get-one/{id}",
  GET_LIST_CATEGORY: "/api/category/get-list",
  EDIT_CATEGORY: "/api/category/update/{id}",
  GET_ONE_CATEGORY: "/api/category/get-one/{id}",
  DELETE_CATEGORY: "/api/category/delete/{id}",
  CREATE_CATEGORY: "/api/category/create",
  GET_LIST_BASIS_CONVERSION: "/api/basis-conversion/get-list",
  EDIT_BASIS_CONVERSION: "/api/basis-conversion/update/{id}",
  GET_ONE_BASIS_CONVERSION: "/api/basis-conversion/get-one/{id}",
  DELETE_BASIS_CONVERSION: "/api/basis-conversion/delete/{id}",
  CREATE_BASIS_CONVERSION: "/api/basis-conversion/create",
  GET_LIST_BASIS_OPTION: "/api/basis-option/get-list",
  EDIT_BASIS_OPTION: "/api/basis-option/update/{id}",
  GET_ONE_BASIS_OPTION: "/api/basis-option/get-one/{id}",
  DELETE_BASIS_OPTION: "/api/basis-option/delete/{id}",
  CREATE_BASIS_OPTION: "/api/basis-option/create",
  GET_LIST_BASIS_PRESET: "/api/basis-preset/get-list",
  EDIT_BASIS_PRESET: "/api/basis-preset/update/{id}",
  GET_ONE_BASIS_PRESET: "/api/basis-preset/get-one/{id}",
  DELETE_BASIS_PRESET: "/api/basis-preset/delete/{id}",
  CREATE_BASIS_PRESET: "/api/basis-preset/create",
  GET_LIST_ATTRIBUTE: "/api/attribute/get-list",
  GET_LIST_CONTENT_TYPE: "/api/attribute/content-type/get-list",
  EDIT_ATTRIBUTE: "/api/attribute/update/{id}",
  DELETE_ATTRIBUTE: "/api/attribute/delete/{id}",
  CREATE_ATTRIBUTE: "/api/attribute/create",
  GET_ONE_ATTRIBUTE: "/api/attribute/get-one/{id}",
  CREATE_PRODUCT: "/api/product/create",
  UPDATE_PRODUCT: "/api/product/update/{id}",
  DELETE_PRODUCT: "/api/product/delete/{id}",
  GET_LIST_PRODUCT: "/api/product/get-list",
  GET_ONE_PRODUCT: "/api/product/get-one/{id}",
  LIKE_OR_UNLIKE_PRODUCT: "/api/product/like/{id}",
  GET_BRAND_PRODUCT_SUMMARY: "/api/product/brand-product-summary/{brand_id}",
  GET_LIST_DOCUMENTATION: "/api/documentation/get-list",
  EDIT_DOCUMENTATION: "/api/documentation/update/{id}",
  DELETE_DOCUMENTATION: "/api/documentation/delete/{id}",
  CREATE_DOCUMENTATION: "/api/documentation/create",
  GET_ONE_DOCUMENTATION: "/api/documentation/get-one/{id}",
  GET_LIST_LOCATION: "/api/location/get-list",
  GET_LIST_LOCATION_WITH_GROUP: "/api/location/get-list-with-country-group",
  GET_ONE_LOCATION: "/api/location/get-one/{id}",
  EDIT_LOCATION: "/api/location/update/{id}",
  DELETE_LOCATION: "/api/location/delete/{id}",
  CREATE_LOCATION: "/api/location/create",
  GET_FUNCTIONAL_TYPES: "/api/functional-type/get-list",
  GET_DEPARTMENTS: "/api/department/get-list",

  GET_COUNTRIES: "/api/location/get-countries",
  GET_STATES: "/api/location/get-states",
  GET_CITIES: "/api/location/get-cities",

  GET_LIST_TEAM_PROFILE: "/api/team-profile/get-list",
  GET_ONE_TEAM_PROFILE: "/api/team-profile/get-one/{id}",
  GET_ME_TEAM_PROFILE: "/api/team-profile/get-me",
  UPDATE_ME_TEAM_PROFILE: "/api/team-profile/update-me",
  UPDATE_AVATAR_TEAM_PROFILE: "/api/team-profile/update-avatar",
  EDIT_TEAM_PROFILE: "/api/team-profile/update/{id}",
  DELETE_TEAM_PROFILE: "/api/team-profile/delete/{id}",
  CREATE_TEAM_PROFILE: "/api/team-profile/create",
  SEND_INVITE_TEAM_PROFILE: "/api/team-profile/invite/{id}",
  GET_LIST_PERMISSION: "/api/permission/get-list",
  OPEN_CLOSE_PERMISSION: "/api/permission/open-close/{id}",
  GET_LIST_EMAIL_AUTO: "/api/email-auto/get-list",
  GET_ONE_EMAIL_AUTO: "/api/email-auto/get-one/{id}",
  EDIT_EMAIL_AUTO: "/api/email-auto/update/{id}",
  DELETE_EMAIL_AUTO: "/api/email-auto/delete/{id}",
  CREATE_EMAIL_AUTO: "/api/email-auto/create",
  GET_LIST_QUOTATION: "/api/quotation/get-list",
  GET_ONE_QUOTATION: "/api/quotation/get-one/{id}",
  EDIT_QUOTATION: "/api/quotation/update/{id}",
  DELETE_QUOTATION: "/api/quotation/delete/{id}",
  CREATE_QUOTATION: "/api/quotation/create",
  GET_LIST_SERVICE: "/api/service/get-list",
  GET_ONE_SERVICE: "/api/service/get-one/{id}",
  CREATE_SERVICE: "/api/service/create",
  GET_LIST_SUBSCRIPTION: "/api/subscription/get-list",
  CREATE_CONTACT: "/api/contact/create",
  GET_LIST_CONTACT: "/api/contact/list",
  GET_ONE_CONTACT: "/api/contact/get-one/{id}",
  GET_ONE_SUBSCRIPTION: "/api/subscription/get-one/{id}",
  GET_LIST_COLLECTION: "/api/collection/get-list",
  CREATE_COLLECTION: "/api/collection/create",
  GET_LIST_REST_COLLECTION_PRODUCT:
    "/api/product/get-list-rest-collection-product/{id}",

  CREATE_PRODUCT_TIP: "/api/product-tip/create",
  GET_LIST_PRODUCT_TIP: "/api/product-tip/get-list",
  GET_ONE_PRODUCT_TIP: "/api/product-tip/get-one/{product_id}",
  EDIT_PRODUCT_TIP: "/api/product-tip/update/{product_id}",
  DELETE_PRODUCT_TIP: "/api/product-tip/delete/{product_id}",
  GET_LIST_PRODUCT_TIP_BY_PRODUCT_ID:
    "/api/product-tip/get-list-by-product/{id}",

  CREATE_PRODUCT_DOWNLOAD: "/api/product-download/create",
  GET_LIST_PRODUCT_DOWNLOAD: "/api/product-download/get-list",
  GET_ONE_PRODUCT_DOWNLOAD: "/api/product-download/get-one/{product_id}",
  EDIT_PRODUCT_DOWNLOAD: "/api/product-download/update/{product_id}",
  DELETE_PRODUCT_DOWNLOAD: "/api/product-download/delete/{product_id}",
  GET_LIST_PRODUCT_DOWNLOAD_BY_PRODUCT_ID:
    "/api/product-download/get-list-by-product/{id}",

  GET_LIST_AUTO_EMAIL_TOPIC: "/api/email-auto/get-list-topic",
  GET_LIST_AUTO_EMAIL_TARGETED_FOR: "/api/email-auto/get-list-targeted-for",

  GET_LIST_PROJECT_CARD: "/api/project/get-list-card",
  CREATE_PROJECT: "/api/project/create",
  UPDATE_PROJECT: "/api/project/update/{id}",
  DELETE_PROJECT: "/api/project/delete/{id}",
  CREATE_INQUIRY: "/api/inquiry/create",
  UPDATE_INQUIRY: "/api/inquiry/update/{id}",
  DELETE_INQUIRY: "/api/inquiry/delete/{id}",
  GET_LIST_INQUIRY: "/api/inquiry/get-list",
  GET_ONE_INQUIRY: "/api/inquiry/get-one/{id}",
  CREATE_DISTRIBUTOR: "/api/distributor/create",
  UPDATE_DISTRIBUTOR: "/api/distributor/update/{id}",
  DELETE_DISTRIBUTOR: "/api/distributor/delete/{id}",
  GET_LIST_DISTRIBUTOR: "/api/distributor/get-list",
  GET_ONE_DISTRIBUTOR: "/api/distributor/get-one/{id}",
  CREATE_MARKET_AVAILABILITY: "/api/market-availability/create",
  UPDATE_MARKET_AVAILABILITY: "/api/market-availability/update/{id}",
  DELETE_MARKET_AVAILABILITY: "/api/market-availability/delete/{id}",
  GET_LIST_MARKET_AVAILABILITY: "/api/market-availability/get-list",
  GET_ONE_MARKET_AVAILABILITY: "/api/market-availability/get-one/{id}",
  UPDATE_DESIGN_PROFILE: "/api/design/update-profile",
  CREATE_PROJECT_SPACE: "/api/project-space/create",
  UPDATE_PROJECT_SPACE: "/api/project-space/update/{id}",
  DELETE_PROJECT_SPACE: "/api/project-space/delete/{id}",
  GET_LIST_PROJECT_SPACE: "/api/project-space/get-list",
  GET_ONE_PROJECT_SPACE: "/api/project-space/get-one/{id}",
  CREATE_MATERIAL_CODE: "/api/material-code/create",
  UPDATE_MATERIAL_CODE: "/api/material-code/update/{id}",
  DELETE_MATERIAL_CODE: "/api/material-code/delete/{id}",
  GET_LIST_MATERIAL_CODE: "/api/material-code/get-list",
  GET_ONE_MATERIAL_CODE: "/api/material-code/get-one/{id}",
  GET_ALL_ATTRIBUTE: "/api/attribute/get-all",

  CREATE_PRODUCT_CATELOGUE_DOWNLOAD: "/api/product-catelogue-download/create",
  GET_LIST_PRODUCT_CATELOGUE_DOWNLOAD:
    "/api/product-catelogue-download/get-list",
  GET_ONE_PRODUCT_CATELOGUE_DOWNLOAD:
    "/api/product-catelogue-download/get-one/{product_id}",
  EDIT_PRODUCT_CATELOGUE_DOWNLOAD:
    "/api/product-catelogue-download/update/{product_id}",
  DELETE_PRODUCT_CATELOGUE_DOWNLOAD:
    "/api/product-catelogue-download/delete/{product_id}",

  GET_COUNTRY: "/api/location/get-country/{id}",
  GET_STATE: "/api/location/get-state/{id}",
  GET_CITY: "/api/location/get-city/{id}",

  CREATE_BRAND: "/api/brand/create",
  DUPLICATE_PRODUCT: "/api/product/duplicate/{id}",
  UPDATE_HOWTO: "/api/documentation/howto/update",
  GET_ALL_HOWTO: "/api/documentation/howto/get-all",
  GET_ALL_BRAND_SUMMARY: "/api/brand/summary",
  DELETE_COLLECTION: "/api/collection/delete/{id}",
  GET_LIST_DESIGNER_BRAND_PRODUCTS: "/api/product/design/get-list",
  GET_PROJECT_TYPES: "/api/project/project-types",
  GET_BUILDING_TYPES: "/api/project/building-types",
};
const ROUTE_IDS = {
  GET_LIST_BRAND: "1",
  GET_LIST_BRAND_CARD: "2",
  GET_LIST_BRAND_BY_ALPHABET: "3",
  GET_ONE_BRAND: "4",
  UPDATE_BRAND: "5",
  UPDATE_BRAND_PROFILE: "6",
  UPDATE_BRAND_LOGO: "7",
  GET_BRAND_STATUSES: "8",
  SEND_EMAIL_INVITE_BRAND: "9",
  GET_LIST_ASSIGN_TEAM: "10",
  ASSIGN_TEAM: "11",
  GET_LIST_DESIGN_FIRM: "12",
  GET_ONE_DESIGN_FIRM: "13",
  UPDATE_DESIGN_FIRM: "14",
  GET_DESIGN_STATUSES: "15",
  GET_LIST_PROJECT: "16",
  GET_ONE_PROJECT: "17",
  GET_LIST_CATEGORY: "18",
  EDIT_CATEGORY: "19",
  GET_ONE_CATEGORY: "20",
  DELETE_CATEGORY: "21",
  CREATE_CATEGORY: "22",
  GET_LIST_BASIS_CONVERSION: "23",
  EDIT_BASIS_CONVERSION: "24",
  GET_ONE_BASIS_CONVERSION: "25",
  DELETE_BASIS_CONVERSION: "26",
  CREATE_BASIS_CONVERSION: "27",
  GET_LIST_BASIS_OPTION: "28",
  EDIT_BASIS_OPTION: "29",
  GET_ONE_BASIS_OPTION: "30",
  DELETE_BASIS_OPTION: "31",
  CREATE_BASIS_OPTION: "32",
  GET_LIST_BASIS_PRESET: "33",
  EDIT_BASIS_PRESET: "34",
  GET_ONE_BASIS_PRESET: "35",
  DELETE_BASIS_PRESET: "36",
  CREATE_BASIS_PRESET: "37",
  GET_LIST_ATTRIBUTE: "38",
  GET_LIST_CONTENT_TYPE: "39",
  EDIT_ATTRIBUTE: "40",
  DELETE_ATTRIBUTE: "41",
  CREATE_ATTRIBUTE: "42",
  GET_ONE_ATTRIBUTE: "43",
  CREATE_PRODUCT: "44",
  UPDATE_PRODUCT: "45",
  DELETE_PRODUCT: "46",
  GET_LIST_PRODUCT: "47",
  GET_ONE_PRODUCT: "48",
  LIKE_OR_UNLIKE_PRODUCT: "49",
  GET_BRAND_PRODUCT_SUMMARY: "50",
  GET_LIST_DOCUMENTATION: "51",
  EDIT_DOCUMENTATION: "52",
  DELETE_DOCUMENTATION: "53",
  CREATE_DOCUMENTATION: "54",
  GET_ONE_DOCUMENTATION: "55",
  GET_LIST_LOCATION: "56",
  GET_LIST_LOCATION_WITH_GROUP: "57",
  GET_ONE_LOCATION: "58",
  EDIT_LOCATION: "59",
  DELETE_LOCATION: "60",
  CREATE_LOCATION: "61",
  GET_FUNCTIONAL_TYPES: "62",
  GET_DEPARTMENTS: "63",

  GET_COUNTRIES: "64",
  GET_STATES: "65",
  GET_CITIES: "66",

  GET_LIST_TEAM_PROFILE: "67",
  GET_ONE_TEAM_PROFILE: "68",
  GET_ME_TEAM_PROFILE: "69",
  UPDATE_ME_TEAM_PROFILE: "70",
  UPDATE_AVATAR_TEAM_PROFILE: "71",
  EDIT_TEAM_PROFILE: "72",
  DELETE_TEAM_PROFILE: "73",
  CREATE_TEAM_PROFILE: "74",
  SEND_INVITE_TEAM_PROFILE: "75",
  GET_LIST_PERMISSION: "76",
  OPEN_CLOSE_PERMISSION: "77",
  GET_LIST_EMAIL_AUTO: "78",
  GET_ONE_EMAIL_AUTO: "79",
  EDIT_EMAIL_AUTO: "80",
  DELETE_EMAIL_AUTO: "81",
  CREATE_EMAIL_AUTO: "82",
  GET_LIST_QUOTATION: "83",
  GET_ONE_QUOTATION: "84",
  EDIT_QUOTATION: "85",
  DELETE_QUOTATION: "86",
  CREATE_QUOTATION: "87",
  GET_LIST_SERVICE: "88",
  GET_ONE_SERVICE: "89",
  CREATE_SERVICE: "90",
  GET_LIST_SUBSCRIPTION: "91",
  CREATE_CONTACT: "92",
  GET_LIST_CONTACT: "93",
  GET_ONE_CONTACT: "94",
  GET_ONE_SUBSCRIPTION: "95",
  GET_LIST_COLLECTION: "96",
  CREATE_COLLECTION: "97",
  GET_LIST_REST_COLLECTION_PRODUCT: "98",

  CREATE_PRODUCT_TIP: "99",
  GET_LIST_PRODUCT_TIP: "100",
  GET_ONE_PRODUCT_TIP: "101",
  EDIT_PRODUCT_TIP: "102",
  DELETE_PRODUCT_TIP: "103",
  GET_LIST_PRODUCT_TIP_BY_PRODUCT_ID: "104",

  CREATE_PRODUCT_DOWNLOAD: "105",
  GET_LIST_PRODUCT_DOWNLOAD: "106",
  GET_ONE_PRODUCT_DOWNLOAD: "107",
  EDIT_PRODUCT_DOWNLOAD: "108",
  DELETE_PRODUCT_DOWNLOAD: "109",
  GET_LIST_PRODUCT_DOWNLOAD_BY_PRODUCT_ID: "110",

  GET_LIST_AUTO_EMAIL_TOPIC: "111",
  GET_LIST_AUTO_EMAIL_TARGETED_FOR: "112",

  GET_LIST_PROJECT_CARD: "113",
  CREATE_PROJECT: "114",
  UPDATE_PROJECT: "115",
  DELETE_PROJECT: "116",
  CREATE_INQUIRY: "117",
  UPDATE_INQUIRY: "118",
  DELETE_INQUIRY: "119",
  GET_LIST_INQUIRY: "120",
  GET_ONE_INQUIRY: "121",
  CREATE_DISTRIBUTOR: "122",
  UPDATE_DISTRIBUTOR: "123",
  DELETE_DISTRIBUTOR: "124",
  GET_LIST_DISTRIBUTOR: "125",
  GET_ONE_DISTRIBUTOR: "126",
  CREATE_MARKET_AVAILABILITY: "127",
  UPDATE_MARKET_AVAILABILITY: "128",
  DELETE_MARKET_AVAILABILITY: "129",
  GET_LIST_MARKET_AVAILABILITY: "130",
  GET_ONE_MARKET_AVAILABILITY: "131",
  UPDATE_DESIGN_PROFILE: "132",
  CREATE_PROJECT_SPACE: "133",
  UPDATE_PROJECT_SPACE: "134",
  DELETE_PROJECT_SPACE: "135",
  GET_LIST_PROJECT_SPACE: "136",
  GET_ONE_PROJECT_SPACE: "137",
  CREATE_MATERIAL_CODE: "138",
  UPDATE_MATERIAL_CODE: "139",
  DELETE_MATERIAL_CODE: "140",
  GET_LIST_MATERIAL_CODE: "141",
  GET_ONE_MATERIAL_CODE: "142",
  GET_ALL_ATTRIBUTE: "143",

  CREATE_PRODUCT_CATELOGUE_DOWNLOAD: "144",
  GET_LIST_PRODUCT_CATELOGUE_DOWNLOAD: "145",
  GET_ONE_PRODUCT_CATELOGUE_DOWNLOAD: "146",
  EDIT_PRODUCT_CATELOGUE_DOWNLOAD: "147",
  DELETE_PRODUCT_CATELOGUE_DOWNLOAD: "148",

  GET_COUNTRY: "149",
  GET_STATE: "150",
  GET_CITY: "151",

  CREATE_BRAND: "152",

  DUPLICATE_PRODUCT: "153",
  UPDATE_HOWTO: "154",
  GET_ALL_HOWTO: "155",
  GET_ALL_BRAND_SUMMARY: "156",
  DELETE_COLLECTION: "157",
  GET_LIST_DESIGNER_BRAND_PRODUCTS: "158",
  GET_PROJECT_TYPES: "159",
  GET_BUILDING_TYPES: "160",
};

const USER_STATUSES = {
  ACTIVE: 1,
  BLOCKED: 2,
  PENDING: 3,
};
const USER_NULL_ATTRIBUTES = {
  id: null,
  role_id: null,
  firstname: null,
  lastname: null,
  gender: null,
  location_id: null,
  department: null,
  position: null,
  email: null,
  phone: null,
  mobile: null,
  password: null,
  avatar: null,
  backup_email: null,
  personal_mobile: null,
  linkedin: null,
  is_verified: null,
  verification_token: null,
  reset_password_token: null,
  status: null,
  created_at: null,
  type: null,
  relation_id: null,
  is_deleted: false,
};
const BRAND_NULL_ATTRIBUTES = {
  id: null,
  name: null,
  parent_company: null,
  logo: null,
  slogan: null,
  mission_n_vision: null,
  official_websites: [],
  team_profile_ids: [],
  location_ids: [],
  status: null,
  created_at: null,
  updated_at: null,
  is_deleted: false,
};
const BRAND_STATUSES = {
  ACTIVE: 1,
  INACTIVE: 2,
  PENDING: 3,
};
const DESIGN_NULL_ATTRIBUTES = {
  id: null,
  name: null,
  parent_company: null,
  logo: null,
  slogan: null,
  profile_n_philosophy: null,
  official_website: null,
  design_capabilities: null,
  team_profile_ids: null,
  location_ids: null,
  material_code_ids: null,
  project_ids: null,
  status: null,
  created_at: null,
  updated_at: null,
  is_deleted: false,
};
const DESIGN_STATUSES = {
  ACTIVE: 1,
  INACTIVE: 2,
};
const CATEGORY_NULL_ATTRIBUTES = {
  id: null,
  name: null,
  subs: null,
  created_at: null,
  is_deleted: false,
};
const FUNCTIONAL_TYPE_NULL_ATTRIBUTES = {
  id: null,
  name: null,
  created_at: null,
  is_deleted: false,
  type: 0,
};
const PROJECT_TYPE_NULL_ATTRIBUTES = {
  id: "",
  name: "",
  created_at: "",
  is_deleted: false,
  type: 0,
  relation_id: "",
};
const BASIS_NULL_ATTRIBUTES = {
  id: null,
  type: null,
  name: null,
  subs: null,
  created_at: null,
  is_deleted: false,
};
const BASIS_TYPES = {
  CONVERSION: 1,
  PRESET: 2,
  OPTION: 3,
};
const DEPARTMENT_NULL_ATTRIBUTES = {
  id: null,
  name: null,
  created_at: null,
  is_deleted: false,
  type: 0,
};

const TOPIC_TYPES = {
  MARKETING: 1,
  MESSAGES: 2,
  ONBOARD: 3,
  OPERATION: 4,
  OTHER: 5,
};

const TARGETED_FOR_TYPES = {
  BRAND: 1,
  DESIGN_FIRM: 2,
  DISTRIBUTOR: 3,
  GENERAL: 4,
  TISC_TEAM: 5,
};

const PERMISSION_NULL_ATTRIBUTES = {
  id: null,
  routes: [],
  role_id: null,
  type: null,
  relation_id: null,
  logo: null,
  name: null,
  accessable: null,
  number: null,
  parent_number: null,
  created_at: null,
};
const DOCUMENTATION_NULL_ATTRIBUTES = {
  id: null,
  logo: null,
  type: null,
  title: null,
  document: {},
  created_at: null,
  created_by: null,
  updated_at: null,
  is_deleted: false,
};
const DOCUMENTATION_TYPES = {
  GENERAL: 1,
  TISC_HOW_TO: 2,
  BRAND_HOW_TO: 3,
  DESIGN_HOW_TO: 4,
};
const LOGO_PATH = {
  MY_WORKSPACE: "/logo/my_workspace.svg",
  USER_GROUP: "/logo/user_group.svg",
  PROJECT: "/logo/project.svg",
  LIST: "/logo/list.svg",
  PRODUCT: "/logo/product.svg",
  ADMINISTRATION: "/logo/administration.svg",
  GENERAL_INQUIRY: "/logo/general_inquires.svg",
  PROJECT_TRACKING: "/logo/project_tracking.svg",
  FAVORITE: "/logo/favourite.svg",
  SUBSCRIPTION: "/logo/subscription.svg",
  MARKET: "/logo/market_availability.svg",
  DISTRIBUTOR: "/logo/distributor.svg",
  REVENUE: "/logo/revenue.svg",
  MESSAGE: "/logo/message.svg",
  TEAM_PROFILE: "/logo/team_profile.svg",
  LOCATION: "/logo/location.svg",
  DOCUMENTATION: "/logo/documentation.svg",
  CONFIGURATION: "/logo/configuration.svg",
  ATTRIBUTE: "/logo/attribute.svg",
  BASIS: "/logo/basis.svg",
  CATEGORY: "/logo/category.svg",
  BRAND: "/logo/brand.svg",
  DESIGN: "/logo/design.svg",
  OFFICE: "/logo/office.svg",
  MATERIAL: "/logo/material.svg",
};
const BUILDING_TYPE_NULL_ATTRIBUTES = {
  id: "",
  name: "",
  created_at: "",
  is_deleted: false,
  type: 0,
  relation_id: "",
};
module.exports = {
  ROLES,
  PERMISSION_TITLE,
  ROUTES,
  ROUTE_IDS,
  SYSTEM_TYPE,
  USER_STATUSES,
  USER_NULL_ATTRIBUTES,
  BRAND_NULL_ATTRIBUTES,
  BRAND_STATUSES,
  DESIGN_NULL_ATTRIBUTES,
  DESIGN_STATUSES,
  CATEGORY_NULL_ATTRIBUTES,
  FUNCTIONAL_TYPE_NULL_ATTRIBUTES,
  BASIS_NULL_ATTRIBUTES,
  BASIS_TYPES,
  DEPARTMENT_NULL_ATTRIBUTES,
  TOPIC_TYPES,
  TARGETED_FOR_TYPES,
  PERMISSION_NULL_ATTRIBUTES,
  DOCUMENTATION_NULL_ATTRIBUTES,
  DOCUMENTATION_TYPES,
  LOGO_PATH,
  PROJECT_TYPE_NULL_ATTRIBUTES,
  BUILDING_TYPE_NULL_ATTRIBUTES,
};
