const { Database } = require("arangojs");
const dotenv = require("dotenv");
const moment = require("moment");
const uuid = require("uuid").v4;
const ROLES = require("./constant").ROLES;
const PERMISSION_TITLE = require("./constant").PERMISSION_TITLE;
const SYSTEM_TYPE = require("./constant").SYSTEM_TYPE;
const ROUTES = require("./constant").ROUTES;
dotenv.config();

const db = new Database({
  url: process.env.DATABASE_HOSTNAME,
});
db.useDatabase(process.env.DATABASE_NAME || "");
db.useBasicAuth(process.env.DATABASE_USERNAME, process.env.DATABASE_PASSWORD);

const seed = async () => {
  const permissionCollection = await db.collection("permissions");
  const createAndSeed = async (collection) => {
    await collection.create();
    await collection.get();
    const records = [
      {
        id: uuid(),
        routes: [ROUTES.GET_LIST_WORKSPACE],
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/my_workspace.svg",
        name: PERMISSION_TITLE.MY_WORKSPACE,
        accessable: true,
        url: null,
        created_at: moment(),
        number: 1,
        parent_number: null,
      },
      {
        id: uuid(),
        routes: [],
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/user_group.svg",
        name: PERMISSION_TITLE.USER_GROUP,
        accessable: null,
        url: null,
        created_at: moment(),
        number: 2,
        parent_number: null,
      },
      {
        id: uuid(),
        routes: [
          ROUTES.GET_LIST_BRAND,
          ROUTES.GET_ONE_BRAND,
          ROUTES.GET_LIST_BRAND_BY_ALPHABET,
          ROUTES.UPDATE_BRAND,
          ROUTES.SEND_EMAIL_INVITE_BRAND,
        ],
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/brand.svg",
        name: PERMISSION_TITLE.USER_GROUP_BRAND,
        accessable: true,
        url: null,
        created_at: moment(),
        number: 3,
        parent_number: 2,
      },
      {
        id: uuid(),
        routes: [
          ROUTES.UPDATE_DESIGN_FIRM,
          ROUTES.GET_ONE_DESIGN_FIRM,
          ROUTES.GET_LIST_DESIGN_FIRM,
        ],
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/design.svg",
        name: PERMISSION_TITLE.USER_GROUP_DESIGN,
        accessable: true,
        url: null,
        created_at: moment(),
        number: 4,
        parent_number: 2,
      },
      {
        id: uuid(),
        routes: [],
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/project.svg",
        name: PERMISSION_TITLE.PROJECT,
        accessable: null,
        url: null,
        created_at: moment(),
        number: 5,
        parent_number: null,
      },
      {
        id: uuid(),
        routes: [ROUTES.GET_LIST_PROJECT, ROUTES.GET_ONE_PROJECT],
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/list.svg",
        name: PERMISSION_TITLE.PROJECT_LIST,
        accessable: true,
        url: null,
        created_at: moment(),
        number: 6,
        parent_number: 5,
      },
      {
        id: uuid(),
        routes: [],
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/product.svg",
        name: PERMISSION_TITLE.PRODUCT,
        accessable: null,
        url: null,
        created_at: moment(),
        number: 7,
        parent_number: null,
      },
      {
        id: uuid(),
        routes: [
          ROUTES.GET_LIST_CATEGORY,
          ROUTES.CREATE_CATEGORY,
          ROUTES.EDIT_CATEGORY,
          ROUTES.DELETE_CATEGORY,
          ROUTES.GET_ONE_CATEGORY,
        ],
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/category.svg",
        name: PERMISSION_TITLE.PRODUCT_CATEGORY,
        accessable: true,
        url: null,
        created_at: moment(),
        number: 8,
        parent_number: 7,
      },
      {
        id: uuid(),
        routes: [
          ROUTES.GET_LIST_BASIS_CONVERSION,
          ROUTES.EDIT_BASIS_CONVERSION,
          ROUTES.CREATE_BASIS_CONVERSION,
          ROUTES.DELETE_BASIS_CONVERSION,
          ROUTES.GET_ONE_BASIS_CONVERSION,
          ROUTES.GET_LIST_BASIS_PRESET,
          ROUTES.EDIT_BASIS_PRESET,
          ROUTES.CREATE_BASIS_PRESET,
          ROUTES.DELETE_BASIS_PRESET,
          ROUTES.GET_ONE_BASIS_PRESET,
          ROUTES.GET_LIST_BASIS_OPTION,
          ROUTES.EDIT_BASIS_OPTION,
          ROUTES.CREATE_BASIS_OPTION,
          ROUTES.DELETE_BASIS_OPTION,
          ROUTES.GET_ONE_BASIS_OPTION,
        ],
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/basis.svg",
        name: PERMISSION_TITLE.PRODUCT_BASIS,
        accessable: true,
        url: null,
        created_at: moment(),
        number: 9,
        parent_number: 7,
      },
      {
        id: uuid(),
        routes: [
          ROUTES.EDIT_ATTRIBUTE,
          ROUTES.CREATE_ATTRIBUTE,
          ROUTES.DELETE_ATTRIBUTE,
          ROUTES.GET_ONE_ATTRIBUTE,
          ROUTES.GET_LIST_ATTRIBUTE,
          ROUTES.GET_LIST_CONTENT_TYPE,
        ],
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/attribute.svg",
        name: PERMISSION_TITLE.PRODUCT_ATTRIBUTE,
        accessable: true,
        url: null,
        created_at: moment(),
        number: 10,
        parent_number: 7,
      },
      {
        id: uuid(),
        routes: [
          ROUTES.GET_LIST_BRAND_BY_ALPHABET,
          ROUTES.CREATE_PRODUCT,
          ROUTES.UPDATE_PRODUCT,
          ROUTES.GET_ONE_PRODUCT,
          ROUTES.GET_LIST_PRODUCT,
          ROUTES.CREATE_COLLECTION,
          ROUTES.GET_LIST_COLLECTION,
        ],
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/configuration.svg",
        name: PERMISSION_TITLE.PRODUCT_CONFIGURATION,
        accessable: true,
        url: null,
        created_at: moment(),
        number: 11,
        parent_number: 7,
      },
      {
        id: uuid(),
        routes: [],
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/administration.svg",
        name: PERMISSION_TITLE.ADMINISTRATION,
        accessable: null,
        url: null,
        created_at: moment(),
        number: 12,
        parent_number: null,
      },
      {
        id: uuid(),
        routes: [
          ROUTES.EDIT_DOCUMENTATION,
          ROUTES.DELETE_DOCUMENTATION,
          ROUTES.CREATE_DOCUMENTATION,
          ROUTES.GET_ONE_DOCUMENTATION,
          ROUTES.GET_LIST_DOCUMENTATION,
        ],
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/documentation.svg",
        name: PERMISSION_TITLE.ADMINISTRATION_DOCUMENTATION,
        accessable: true,
        url: null,
        created_at: moment(),
        number: 13,
        parent_number: 12,
      },
      {
        id: uuid(),
        routes: [
          ROUTES.EDIT_LOCATION,
          ROUTES.DELETE_LOCATION,
          ROUTES.CREATE_LOCATION,
          ROUTES.GET_ONE_LOCATION,
          ROUTES.GET_LIST_LOCATION,
        ],
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/location.svg",
        name: PERMISSION_TITLE.ADMINISTRATION_LOCATION,
        accessable: true,
        url: null,
        created_at: moment(),
        number: 14,
        parent_number: 12,
      },
      {
        id: uuid(),
        routes: [
          ROUTES.EDIT_TEAM_PROFILE,
          ROUTES.CREATE_TEAM_PROFILE,
          ROUTES.DELETE_TEAM_PROFILE,
          ROUTES.GET_ONE_TEAM_PROFILE,
          ROUTES.GET_LIST_TEAM_PROFILE,
          ROUTES.SEND_INVITE_TEAM_PROFILE,
          ROUTES.GET_LIST_PERMISSION,
          ROUTES.OPEN_CLOSE_PERMISSION,
        ],
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/team_profile.svg",
        name: PERMISSION_TITLE.ADMINISTRATION_TEAM_PROFILE,
        accessable: true,
        url: null,
        created_at: moment(),
        number: 15,
        parent_number: 12,
      },
      {
        id: uuid(),
        routes: [
          ROUTES.GET_LIST_EMAIL_AUTO,
          ROUTES.GET_ONE_EMAIL_AUTO,
          ROUTES.CREATE_EMAIL_AUTO,
          ROUTES.EDIT_EMAIL_AUTO,
          ROUTES.DELETE_EMAIL_AUTO,
          ROUTES.GET_LIST_QUOTATION,
          ROUTES.GET_ONE_QUOTATION,
          ROUTES.CREATE_QUOTATION,
          ROUTES.EDIT_QUOTATION,
          ROUTES.DELETE_QUOTATION,
        ],
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/message.svg",
        name: PERMISSION_TITLE.ADMINISTRATION_MESSAGE,
        accessable: true,
        url: null,
        created_at: moment(),
        number: 16,
        parent_number: 12,
      },
      {
        id: uuid(),
        routes: [
          ROUTES.GET_LIST_SERVICE,
          ROUTES.GET_ONE_SERVICE,
          ROUTES.CREATE_SERVICE,
          ROUTES.GET_LIST_SUBSCRIPTION,
          ROUTES.GET_ONE_SUBSCRIPTION,
        ],
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/revenue.svg",
        name: PERMISSION_TITLE.ADMINISTRATION_REVENUE,
        accessable: true,
        url: null,
        created_at: moment(),
        number: 17,
        parent_number: 12,
      },
      //consultant team
      {
        id: uuid(),
        routes: [ROUTES.GET_LIST_WORKSPACE],
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/my_workspace.svg",
        name: PERMISSION_TITLE.MY_WORKSPACE,
        accessable: true,
        url: null,
        created_at: moment(),
        number: 1,
        parent_number: null,
      },
      {
        id: uuid(),
        routes: [],
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/user_group.svg",
        name: PERMISSION_TITLE.USER_GROUP,
        accessable: null,
        url: null,
        created_at: moment(),
        number: 2,
        parent_number: null,
      },
      {
        id: uuid(),
        routes: [
          ROUTES.GET_LIST_BRAND,
          ROUTES.GET_ONE_BRAND,
          ROUTES.GET_LIST_BRAND_BY_ALPHABET,
          ROUTES.UPDATE_BRAND,
          ROUTES.SEND_EMAIL_INVITE_BRAND,
        ],
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/brand.svg",
        name: PERMISSION_TITLE.USER_GROUP_BRAND,
        accessable: false,
        url: null,
        created_at: moment(),
        number: 3,
        parent_number: 2,
      },
      {
        id: uuid(),
        routes: [
          ROUTES.UPDATE_DESIGN_FIRM,
          ROUTES.GET_ONE_DESIGN_FIRM,
          ROUTES.GET_LIST_DESIGN_FIRM,
        ],
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/design.svg",
        name: PERMISSION_TITLE.USER_GROUP_DESIGN,
        accessable: false,
        url: null,
        created_at: moment(),
        number: 4,
        parent_number: 2,
      },
      {
        id: uuid(),
        routes: [],
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/project.svg",
        name: PERMISSION_TITLE.PROJECT,
        accessable: null,
        url: null,
        created_at: moment(),
        number: 5,
        parent_number: null,
      },
      {
        id: uuid(),
        routes: [ROUTES.GET_LIST_PROJECT, ROUTES.GET_ONE_PROJECT],
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/list.svg",
        name: PERMISSION_TITLE.PROJECT_LIST,
        accessable: false,
        url: null,
        created_at: moment(),
        number: 6,
        parent_number: 5,
      },
      {
        id: uuid(),
        routes: [],
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/product.svg",
        name: PERMISSION_TITLE.PRODUCT,
        accessable: null,
        url: null,
        created_at: moment(),
        number: 7,
        parent_number: null,
      },
      {
        id: uuid(),
        routes: [
          ROUTES.GET_LIST_CATEGORY,
          ROUTES.CREATE_CATEGORY,
          ROUTES.EDIT_CATEGORY,
          ROUTES.DELETE_CATEGORY,
          ROUTES.GET_ONE_CATEGORY,
        ],
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/category.svg",
        name: PERMISSION_TITLE.PRODUCT_CATEGORY,
        accessable: false,
        url: null,
        created_at: moment(),
        number: 8,
        parent_number: 7,
      },
      {
        id: uuid(),
        routes: [
          ROUTES.GET_LIST_BASIS_CONVERSION,
          ROUTES.EDIT_BASIS_CONVERSION,
          ROUTES.CREATE_BASIS_CONVERSION,
          ROUTES.DELETE_BASIS_CONVERSION,
          ROUTES.GET_ONE_BASIS_CONVERSION,
          ROUTES.GET_LIST_BASIS_PRESET,
          ROUTES.EDIT_BASIS_PRESET,
          ROUTES.CREATE_BASIS_PRESET,
          ROUTES.DELETE_BASIS_PRESET,
          ROUTES.GET_ONE_BASIS_PRESET,
          ROUTES.GET_LIST_BASIS_OPTION,
          ROUTES.EDIT_BASIS_OPTION,
          ROUTES.CREATE_BASIS_OPTION,
          ROUTES.DELETE_BASIS_OPTION,
          ROUTES.GET_ONE_BASIS_OPTION,
        ],
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/basis.svg",
        name: PERMISSION_TITLE.PRODUCT_BASIS,
        accessable: true,
        url: null,
        created_at: moment(),
        number: 9,
        parent_number: 7,
      },
      {
        id: uuid(),
        routes: [
          ROUTES.EDIT_ATTRIBUTE,
          ROUTES.CREATE_ATTRIBUTE,
          ROUTES.DELETE_ATTRIBUTE,
          ROUTES.GET_ONE_ATTRIBUTE,
          ROUTES.GET_LIST_ATTRIBUTE,
          ROUTES.GET_LIST_CONTENT_TYPE,
        ],
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/attribute.svg",
        name: PERMISSION_TITLE.PRODUCT_ATTRIBUTE,
        accessable: true,
        url: null,
        created_at: moment(),
        number: 10,
        parent_number: 7,
      },
      {
        id: uuid(),
        routes: [
          ROUTES.GET_LIST_BRAND_BY_ALPHABET,
          ROUTES.CREATE_PRODUCT,
          ROUTES.UPDATE_PRODUCT,
          ROUTES.GET_ONE_PRODUCT,
          ROUTES.GET_LIST_PRODUCT,
          ROUTES.CREATE_COLLECTION,
          ROUTES.GET_LIST_COLLECTION,
        ],
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/configuration.svg",
        name: PERMISSION_TITLE.PRODUCT_CONFIGURATION,
        accessable: true,
        url: null,
        created_at: moment(),
        number: 11,
        parent_number: 7,
      },
      {
        id: uuid(),
        routes: [],
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/administration.svg",
        name: PERMISSION_TITLE.ADMINISTRATION,
        accessable: null,
        url: null,
        created_at: moment(),
        number: 12,
        parent_number: null,
      },
      {
        id: uuid(),
        routes: [
          ROUTES.EDIT_DOCUMENTATION,
          ROUTES.DELETE_DOCUMENTATION,
          ROUTES.CREATE_DOCUMENTATION,
          ROUTES.GET_ONE_DOCUMENTATION,
          ROUTES.GET_LIST_DOCUMENTATION,
        ],
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/documentation.svg",
        name: PERMISSION_TITLE.ADMINISTRATION_DOCUMENTATION,
        accessable: false,
        url: null,
        created_at: moment(),
        number: 13,
        parent_number: 12,
      },
      {
        id: uuid(),
        routes: [
          ROUTES.EDIT_LOCATION,
          ROUTES.DELETE_LOCATION,
          ROUTES.CREATE_LOCATION,
          ROUTES.GET_ONE_LOCATION,
          ROUTES.GET_LIST_LOCATION,
        ],
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/location.svg",
        name: PERMISSION_TITLE.ADMINISTRATION_LOCATION,
        accessable: false,
        url: null,
        created_at: moment(),
        number: 14,
        parent_number: 12,
      },
      {
        id: uuid(),
        routes: [
          ROUTES.EDIT_TEAM_PROFILE,
          ROUTES.CREATE_TEAM_PROFILE,
          ROUTES.DELETE_TEAM_PROFILE,
          ROUTES.GET_ONE_TEAM_PROFILE,
          ROUTES.GET_LIST_TEAM_PROFILE,
          ROUTES.SEND_INVITE_TEAM_PROFILE,
          ROUTES.GET_LIST_PERMISSION,
          ROUTES.OPEN_CLOSE_PERMISSION,
        ],
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/team_profile.svg",
        name: PERMISSION_TITLE.ADMINISTRATION_TEAM_PROFILE,
        accessable: false,
        url: null,
        created_at: moment(),
        number: 15,
        parent_number: 12,
      },
      {
        id: uuid(),
        routes: [
          ROUTES.GET_LIST_EMAIL_AUTO,
          ROUTES.GET_ONE_EMAIL_AUTO,
          ROUTES.CREATE_EMAIL_AUTO,
          ROUTES.EDIT_EMAIL_AUTO,
          ROUTES.DELETE_EMAIL_AUTO,
          ROUTES.GET_LIST_QUOTATION,
          ROUTES.GET_ONE_QUOTATION,
          ROUTES.CREATE_QUOTATION,
          ROUTES.EDIT_QUOTATION,
          ROUTES.DELETE_QUOTATION,
        ],
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/message.svg",
        name: PERMISSION_TITLE.ADMINISTRATION_MESSAGE,
        accessable: false,
        url: null,
        created_at: moment(),
        number: 16,
        parent_number: 12,
      },
      {
        id: uuid(),
        routes: [
          ROUTES.GET_LIST_SERVICE,
          ROUTES.GET_ONE_SERVICE,
          ROUTES.CREATE_SERVICE,
          ROUTES.GET_LIST_SUBSCRIPTION,
          ROUTES.GET_ONE_SUBSCRIPTION,
        ],
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        relation_id: null,
        logo: "/logo/revenue.svg",
        name: PERMISSION_TITLE.ADMINISTRATION_REVENUE,
        accessable: false,
        url: null,
        created_at: moment(),
        number: 17,
        parent_number: 12,
      },
    ];

    records.forEach(async (record) => {
      await db.query({
        query: `insert ${JSON.stringify(record)} into @@model`,
        bindVars: {
          "@model": "permissions",
        },
      });
    });
    console.log("success seed tisc permssion data");
  };
  try {
    await createAndSeed(permissionCollection);
  } catch (error) {
    if (error.message === "duplicate name") {
      await permissionCollection.drop();
      await createAndSeed(permissionCollection);
    }
  }
};

module.exports = {
  seedPermission: seed,
};
