const moment = require("moment");
const uuid = require("uuid").v4;
const ROLES = require("./constant").ROLES;
const ROUTE_IDS = require("./constant").ROUTE_IDS;
const PERMISSION_TITLE = require("./constant").PERMISSION_TITLE;
const PERMISSION_NULL_ATTRIBUTES =
  require("./constant").PERMISSION_NULL_ATTRIBUTES;
const SYSTEM_TYPE = require("./constant").SYSTEM_TYPE;
const LOGO_PATH = require("./constant").LOGO_PATH;

const seed = async (db) => {
  const permissionCollection = await db.collection("permissions");
  const createAndSeed = async (collection) => {
    await collection.create();
    await collection.get();
    const records = [
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.MY_WORKSPACE,
        name: PERMISSION_TITLE.MY_WORKSPACE,
        accessable: true,
        created_at: moment(),
        number: 1,
        routes: [{ id: ROUTE_IDS.GET_LIST_BRAND_CARD, accessable: true }],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.USER_GROUP,
        name: PERMISSION_TITLE.USER_GROUP,
        created_at: moment(),
        number: 2,
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.BRAND,
        name: PERMISSION_TITLE.USER_GROUP_BRAND,
        accessable: true,
        created_at: moment(),
        number: 3,
        parent_number: 2,
        routes: [
          { id: ROUTE_IDS.GET_LIST_BRAND, accessable: true },
          { id: ROUTE_IDS.GET_ONE_BRAND, accessable: true },
          { id: ROUTE_IDS.GET_LIST_BRAND_BY_ALPHABET, accessable: true },
          { id: ROUTE_IDS.UPDATE_BRAND, accessable: true },
          { id: ROUTE_IDS.SEND_EMAIL_INVITE_BRAND, accessable: true },
        ],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.DESIGN,
        name: PERMISSION_TITLE.USER_GROUP_DESIGN,
        accessable: true,
        created_at: moment(),
        number: 4,
        parent_number: 2,
        routes: [
          { id: ROUTE_IDS.GET_LIST_DESIGN_FIRM, accessable: true },
          { id: ROUTE_IDS.GET_ONE_DESIGN_FIRM, accessable: true },
          { id: ROUTE_IDS.UPDATE_DESIGN_FIRM, accessable: true },
        ],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.PROJECT,
        name: PERMISSION_TITLE.PROJECT,
        created_at: moment(),
        number: 5,
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.LIST,
        name: PERMISSION_TITLE.PROJECT_LIST,
        accessable: true,
        created_at: moment(),
        number: 6,
        parent_number: 5,
        routes: [
          { id: ROUTE_IDS.GET_LIST_PROJECT, accessable: true },
          { id: ROUTE_IDS.GET_ONE_PROJECT, accessable: true },
        ],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.PRODUCT,
        name: PERMISSION_TITLE.PRODUCT,
        created_at: moment(),
        number: 7,
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.CATEGORY,
        name: PERMISSION_TITLE.PRODUCT_CATEGORY,
        accessable: true,
        created_at: moment(),
        number: 8,
        parent_number: 7,
        routes: [
          { id: ROUTE_IDS.GET_LIST_CATEGORY, accessable: true },
          { id: ROUTE_IDS.EDIT_CATEGORY, accessable: true },
          { id: ROUTE_IDS.GET_ONE_CATEGORY, accessable: true },
          { id: ROUTE_IDS.DELETE_CATEGORY, accessable: true },
          { id: ROUTE_IDS.CREATE_CATEGORY, accessable: true },
        ],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.BASIS,
        name: PERMISSION_TITLE.PRODUCT_BASIS,
        accessable: true,
        created_at: moment(),
        number: 9,
        parent_number: 7,
        routes: [
          { id: ROUTE_IDS.GET_LIST_BASIS_CONVERSION, accessable: true },
          { id: ROUTE_IDS.EDIT_BASIS_CONVERSION, accessable: true },
          { id: ROUTE_IDS.GET_ONE_BASIS_CONVERSION, accessable: true },
          { id: ROUTE_IDS.DELETE_BASIS_CONVERSION, accessable: true },
          { id: ROUTE_IDS.CREATE_BASIS_CONVERSION, accessable: true },
          { id: ROUTE_IDS.GET_LIST_BASIS_OPTION, accessable: true },
          { id: ROUTE_IDS.EDIT_BASIS_OPTION, accessable: true },
          { id: ROUTE_IDS.GET_ONE_BASIS_OPTION, accessable: true },
          { id: ROUTE_IDS.DELETE_BASIS_OPTION, accessable: true },
          { id: ROUTE_IDS.CREATE_BASIS_OPTION, accessable: true },
          { id: ROUTE_IDS.GET_LIST_BASIS_PRESET, accessable: true },
          { id: ROUTE_IDS.EDIT_BASIS_PRESET, accessable: true },
          { id: ROUTE_IDS.GET_ONE_BASIS_PRESET, accessable: true },
          { id: ROUTE_IDS.DELETE_BASIS_PRESET, accessable: true },
          { id: ROUTE_IDS.CREATE_BASIS_PRESET, accessable: true },
        ],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.ATTRIBUTE,
        name: PERMISSION_TITLE.PRODUCT_ATTRIBUTE,
        accessable: true,
        created_at: moment(),
        number: 10,
        parent_number: 7,
        routes: [
          { id: ROUTE_IDS.GET_LIST_ATTRIBUTE, accessable: true },
          { id: ROUTE_IDS.GET_LIST_CONTENT_TYPE, accessable: true },
          { id: ROUTE_IDS.EDIT_ATTRIBUTE, accessable: true },
          { id: ROUTE_IDS.DELETE_ATTRIBUTE, accessable: true },
          { id: ROUTE_IDS.CREATE_ATTRIBUTE, accessable: true },
          { id: ROUTE_IDS.GET_ONE_ATTRIBUTE, accessable: true },
          { id: ROUTE_IDS.GET_ALL_ATTRIBUTE, accessable: true },
        ],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.CONFIGURATION,
        name: PERMISSION_TITLE.PRODUCT_CONFIGURATION,
        accessable: true,
        created_at: moment(),
        number: 11,
        parent_number: 7,
        routes: [
          { id: ROUTE_IDS.CREATE_PRODUCT, accessable: true },
          { id: ROUTE_IDS.UPDATE_PRODUCT, accessable: true },
          { id: ROUTE_IDS.DELETE_PRODUCT, accessable: true },
          { id: ROUTE_IDS.GET_LIST_PRODUCT, accessable: true },
          { id: ROUTE_IDS.GET_ONE_PRODUCT, accessable: true },
          { id: ROUTE_IDS.GET_BRAND_PRODUCT_SUMMARY, accessable: true },

          { id: ROUTE_IDS.CREATE_PRODUCT_CATELOGUE_DOWNLOAD, accessable: true },
          { id: ROUTE_IDS.EDIT_PRODUCT_CATELOGUE_DOWNLOAD, accessable: true },
          { id: ROUTE_IDS.DELETE_PRODUCT_CATELOGUE_DOWNLOAD, accessable: true },

          { id: ROUTE_IDS.CREATE_PRODUCT_TIP, accessable: true },
          { id: ROUTE_IDS.EDIT_PRODUCT_TIP, accessable: true },
          { id: ROUTE_IDS.DELETE_PRODUCT_TIP, accessable: true },

          { id: ROUTE_IDS.CREATE_PRODUCT_DOWNLOAD, accessable: true },
          { id: ROUTE_IDS.EDIT_PRODUCT_DOWNLOAD, accessable: true },
          { id: ROUTE_IDS.DELETE_PRODUCT_DOWNLOAD, accessable: true },
        ],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.ADMINISTRATION,
        name: PERMISSION_TITLE.ADMINISTRATION,
        created_at: moment(),
        number: 12,
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.DOCUMENTATION,
        name: PERMISSION_TITLE.ADMINISTRATION_DOCUMENTATION,
        accessable: true,
        created_at: moment(),
        number: 13,
        parent_number: 12,
        routes: [
          { id: ROUTE_IDS.GET_LIST_DOCUMENTATION, accessable: true },
          { id: ROUTE_IDS.EDIT_DOCUMENTATION, accessable: true },
          { id: ROUTE_IDS.DELETE_DOCUMENTATION, accessable: true },
          { id: ROUTE_IDS.CREATE_DOCUMENTATION, accessable: true },
          { id: ROUTE_IDS.GET_ONE_DOCUMENTATION, accessable: true },
        ],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.LOCATION,
        name: PERMISSION_TITLE.ADMINISTRATION_LOCATION,
        accessable: true,
        created_at: moment(),
        number: 14,
        parent_number: 12,
        routes: [
          { id: ROUTE_IDS.GET_LIST_LOCATION, accessable: true },
          { id: ROUTE_IDS.GET_LIST_LOCATION_WITH_GROUP, accessable: true },
          { id: ROUTE_IDS.GET_ONE_LOCATION, accessable: true },
          { id: ROUTE_IDS.EDIT_LOCATION, accessable: true },
          { id: ROUTE_IDS.DELETE_LOCATION, accessable: true },
          { id: ROUTE_IDS.CREATE_LOCATION, accessable: true },
        ],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.TEAM_PROFILE,
        name: PERMISSION_TITLE.ADMINISTRATION_TEAM_PROFILE,
        accessable: true,
        created_at: moment(),
        number: 15,
        parent_number: 12,
        routes: [
          { id: ROUTE_IDS.GET_LIST_TEAM_PROFILE, accessable: true },
          { id: ROUTE_IDS.GET_ONE_TEAM_PROFILE, accessable: true },
          { id: ROUTE_IDS.EDIT_TEAM_PROFILE, accessable: true },
          { id: ROUTE_IDS.DELETE_TEAM_PROFILE, accessable: true },
          { id: ROUTE_IDS.CREATE_TEAM_PROFILE, accessable: true },
          { id: ROUTE_IDS.SEND_INVITE_TEAM_PROFILE, accessable: true },
          { id: ROUTE_IDS.GET_LIST_PERMISSION, accessable: true },
          { id: ROUTE_IDS.OPEN_CLOSE_PERMISSION, accessable: true },
        ],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.MESSAGE,
        name: PERMISSION_TITLE.ADMINISTRATION_MESSAGE,
        accessable: true,
        created_at: moment(),
        number: 16,
        parent_number: 12,
        routes: [
          { id: ROUTE_IDS.GET_LIST_EMAIL_AUTO, accessable: true },
          { id: ROUTE_IDS.GET_ONE_EMAIL_AUTO, accessable: true },
          { id: ROUTE_IDS.EDIT_EMAIL_AUTO, accessable: true },
          { id: ROUTE_IDS.DELETE_EMAIL_AUTO, accessable: true },
          { id: ROUTE_IDS.CREATE_EMAIL_AUTO, accessable: true },
          { id: ROUTE_IDS.GET_LIST_QUOTATION, accessable: true },
          { id: ROUTE_IDS.GET_ONE_QUOTATION, accessable: true },
          { id: ROUTE_IDS.EDIT_QUOTATION, accessable: true },
          { id: ROUTE_IDS.DELETE_QUOTATION, accessable: true },
          { id: ROUTE_IDS.CREATE_QUOTATION, accessable: true },
        ],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.REVENUE,
        name: PERMISSION_TITLE.ADMINISTRATION_REVENUE,
        accessable: true,
        created_at: moment(),
        number: 17,
        parent_number: 12,
        routes: [
          { id: ROUTE_IDS.GET_LIST_SERVICE, accessable: true },
          { id: ROUTE_IDS.GET_ONE_SERVICE, accessable: true },
          { id: ROUTE_IDS.CREATE_SERVICE, accessable: true },
          { id: ROUTE_IDS.GET_LIST_SUBSCRIPTION, accessable: true },
          { id: ROUTE_IDS.GET_ONE_SUBSCRIPTION, accessable: true },
        ],
      },
      //consultant team
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.MY_WORKSPACE,
        name: PERMISSION_TITLE.MY_WORKSPACE,
        accessable: true,
        created_at: moment(),
        number: 1,
        routes: [{ id: ROUTE_IDS.GET_LIST_BRAND_CARD, accessable: true }],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.USER_GROUP,
        name: PERMISSION_TITLE.USER_GROUP,
        created_at: moment(),
        number: 2,
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.BRAND,
        name: PERMISSION_TITLE.USER_GROUP_BRAND,
        accessable: false,
        created_at: moment(),
        number: 3,
        parent_number: 2,
        routes: [
          { id: ROUTE_IDS.GET_LIST_BRAND, accessable: false },
          { id: ROUTE_IDS.GET_ONE_BRAND, accessable: false },
          { id: ROUTE_IDS.GET_LIST_BRAND_BY_ALPHABET, accessable: false },
          { id: ROUTE_IDS.UPDATE_BRAND, accessable: false },
          { id: ROUTE_IDS.SEND_EMAIL_INVITE_BRAND, accessable: false },
        ],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.DESIGN,
        name: PERMISSION_TITLE.USER_GROUP_DESIGN,
        accessable: false,
        created_at: moment(),
        number: 4,
        parent_number: 2,
        routes: [
          { id: ROUTE_IDS.GET_LIST_DESIGN_FIRM, accessable: false },
          { id: ROUTE_IDS.GET_ONE_DESIGN_FIRM, accessable: false },
          { id: ROUTE_IDS.UPDATE_DESIGN_FIRM, accessable: false },
        ],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.PROJECT,
        name: PERMISSION_TITLE.PROJECT,
        created_at: moment(),
        number: 5,
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.LIST,
        name: PERMISSION_TITLE.PROJECT_LIST,
        accessable: false,
        created_at: moment(),
        number: 6,
        parent_number: 5,
        routes: [
          { id: ROUTE_IDS.GET_LIST_PROJECT, accessable: false },
          { id: ROUTE_IDS.GET_ONE_PROJECT, accessable: false },
        ],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.PRODUCT,
        name: PERMISSION_TITLE.PRODUCT,
        created_at: moment(),
        number: 7,
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.CATEGORY,
        name: PERMISSION_TITLE.PRODUCT_CATEGORY,
        accessable: false,
        created_at: moment(),
        number: 8,
        parent_number: 7,
        routes: [
          { id: ROUTE_IDS.GET_LIST_CATEGORY, accessable: false },
          { id: ROUTE_IDS.EDIT_CATEGORY, accessable: false },
          { id: ROUTE_IDS.GET_ONE_CATEGORY, accessable: false },
          { id: ROUTE_IDS.DELETE_CATEGORY, accessable: false },
          { id: ROUTE_IDS.CREATE_CATEGORY, accessable: false },
        ],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.BASIS,
        name: PERMISSION_TITLE.PRODUCT_BASIS,
        accessable: true,
        created_at: moment(),
        number: 9,
        parent_number: 7,
        routes: [
          { id: ROUTE_IDS.GET_LIST_BASIS_CONVERSION, accessable: true },
          { id: ROUTE_IDS.EDIT_BASIS_CONVERSION, accessable: true },
          { id: ROUTE_IDS.GET_ONE_BASIS_CONVERSION, accessable: true },
          { id: ROUTE_IDS.DELETE_BASIS_CONVERSION, accessable: true },
          { id: ROUTE_IDS.CREATE_BASIS_CONVERSION, accessable: true },
          { id: ROUTE_IDS.GET_LIST_BASIS_OPTION, accessable: true },
          { id: ROUTE_IDS.EDIT_BASIS_OPTION, accessable: true },
          { id: ROUTE_IDS.GET_ONE_BASIS_OPTION, accessable: true },
          { id: ROUTE_IDS.DELETE_BASIS_OPTION, accessable: true },
          { id: ROUTE_IDS.CREATE_BASIS_OPTION, accessable: true },
          { id: ROUTE_IDS.GET_LIST_BASIS_PRESET, accessable: true },
          { id: ROUTE_IDS.EDIT_BASIS_PRESET, accessable: true },
          { id: ROUTE_IDS.GET_ONE_BASIS_PRESET, accessable: true },
          { id: ROUTE_IDS.DELETE_BASIS_PRESET, accessable: true },
          { id: ROUTE_IDS.CREATE_BASIS_PRESET, accessable: true },
        ],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.ATTRIBUTE,
        name: PERMISSION_TITLE.PRODUCT_ATTRIBUTE,
        accessable: true,
        created_at: moment(),
        number: 10,
        parent_number: 7,
        routes: [
          { id: ROUTE_IDS.GET_LIST_ATTRIBUTE, accessable: true },
          { id: ROUTE_IDS.GET_LIST_CONTENT_TYPE, accessable: true },
          { id: ROUTE_IDS.EDIT_ATTRIBUTE, accessable: true },
          { id: ROUTE_IDS.DELETE_ATTRIBUTE, accessable: true },
          { id: ROUTE_IDS.CREATE_ATTRIBUTE, accessable: true },
          { id: ROUTE_IDS.GET_ONE_ATTRIBUTE, accessable: true },
          { id: ROUTE_IDS.GET_ALL_ATTRIBUTE, accessable: true },
        ],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.CONFIGURATION,
        name: PERMISSION_TITLE.PRODUCT_CONFIGURATION,
        accessable: true,
        created_at: moment(),
        number: 11,
        parent_number: 7,
        routes: [
          { id: ROUTE_IDS.CREATE_PRODUCT, accessable: true },
          { id: ROUTE_IDS.UPDATE_PRODUCT, accessable: true },
          { id: ROUTE_IDS.DELETE_PRODUCT, accessable: true },
          { id: ROUTE_IDS.GET_LIST_PRODUCT, accessable: true },
          { id: ROUTE_IDS.GET_ONE_PRODUCT, accessable: true },
          { id: ROUTE_IDS.GET_BRAND_PRODUCT_SUMMARY, accessable: true },

          { id: ROUTE_IDS.CREATE_PRODUCT_CATELOGUE_DOWNLOAD, accessable: true },
          { id: ROUTE_IDS.EDIT_PRODUCT_CATELOGUE_DOWNLOAD, accessable: true },
          { id: ROUTE_IDS.DELETE_PRODUCT_CATELOGUE_DOWNLOAD, accessable: true },

          { id: ROUTE_IDS.CREATE_PRODUCT_TIP, accessable: true },
          { id: ROUTE_IDS.EDIT_PRODUCT_TIP, accessable: true },
          { id: ROUTE_IDS.DELETE_PRODUCT_TIP, accessable: true },

          { id: ROUTE_IDS.CREATE_PRODUCT_DOWNLOAD, accessable: true },
          { id: ROUTE_IDS.EDIT_PRODUCT_DOWNLOAD, accessable: true },
          { id: ROUTE_IDS.DELETE_PRODUCT_DOWNLOAD, accessable: true },
        ],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        routes: [],
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.ADMINISTRATION,
        name: PERMISSION_TITLE.ADMINISTRATION,
        created_at: moment(),
        number: 12,
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.DOCUMENTATION,
        name: PERMISSION_TITLE.ADMINISTRATION_DOCUMENTATION,
        accessable: false,
        created_at: moment(),
        number: 13,
        parent_number: 12,
        routes: [
          { id: ROUTE_IDS.GET_LIST_DOCUMENTATION, accessable: false },
          { id: ROUTE_IDS.EDIT_DOCUMENTATION, accessable: false },
          { id: ROUTE_IDS.DELETE_DOCUMENTATION, accessable: false },
          { id: ROUTE_IDS.CREATE_DOCUMENTATION, accessable: false },
          { id: ROUTE_IDS.GET_ONE_DOCUMENTATION, accessable: false },
        ],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.LOCATION,
        name: PERMISSION_TITLE.ADMINISTRATION_LOCATION,
        accessable: false,
        created_at: moment(),
        number: 14,
        parent_number: 12,
        routes: [
          { id: ROUTE_IDS.GET_LIST_LOCATION, accessable: false },
          { id: ROUTE_IDS.GET_LIST_LOCATION_WITH_GROUP, accessable: false },
          { id: ROUTE_IDS.GET_ONE_LOCATION, accessable: false },
          { id: ROUTE_IDS.EDIT_LOCATION, accessable: false },
          { id: ROUTE_IDS.DELETE_LOCATION, accessable: false },
          { id: ROUTE_IDS.CREATE_LOCATION, accessable: false },
        ],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.TEAM_PROFILE,
        name: PERMISSION_TITLE.ADMINISTRATION_TEAM_PROFILE,
        accessable: false,
        created_at: moment(),
        number: 15,
        parent_number: 12,
        routes: [
          { id: ROUTE_IDS.GET_LIST_TEAM_PROFILE, accessable: false },
          { id: ROUTE_IDS.GET_ONE_TEAM_PROFILE, accessable: false },
          { id: ROUTE_IDS.EDIT_TEAM_PROFILE, accessable: false },
          { id: ROUTE_IDS.DELETE_TEAM_PROFILE, accessable: false },
          { id: ROUTE_IDS.CREATE_TEAM_PROFILE, accessable: false },
          { id: ROUTE_IDS.SEND_INVITE_TEAM_PROFILE, accessable: false },
          { id: ROUTE_IDS.GET_LIST_PERMISSION, accessable: false },
          { id: ROUTE_IDS.OPEN_CLOSE_PERMISSION, accessable: false },
        ],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.MESSAGE,
        name: PERMISSION_TITLE.ADMINISTRATION_MESSAGE,
        accessable: false,
        created_at: moment(),
        number: 16,
        parent_number: 12,
        routes: [
          { id: ROUTE_IDS.GET_LIST_EMAIL_AUTO, accessable: false },
          { id: ROUTE_IDS.GET_ONE_EMAIL_AUTO, accessable: false },
          { id: ROUTE_IDS.EDIT_EMAIL_AUTO, accessable: false },
          { id: ROUTE_IDS.DELETE_EMAIL_AUTO, accessable: false },
          { id: ROUTE_IDS.CREATE_EMAIL_AUTO, accessable: false },
          { id: ROUTE_IDS.GET_LIST_QUOTATION, accessable: false },
          { id: ROUTE_IDS.GET_ONE_QUOTATION, accessable: false },
          { id: ROUTE_IDS.EDIT_QUOTATION, accessable: false },
          { id: ROUTE_IDS.DELETE_QUOTATION, accessable: false },
          { id: ROUTE_IDS.CREATE_QUOTATION, accessable: false },
        ],
      },
      {
        ...PERMISSION_NULL_ATTRIBUTES,
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        type: SYSTEM_TYPE.TISC,
        logo: LOGO_PATH.REVENUE,
        name: PERMISSION_TITLE.ADMINISTRATION_REVENUE,
        accessable: false,
        created_at: moment(),
        number: 17,
        parent_number: 12,
        routes: [
          { id: ROUTE_IDS.GET_LIST_SERVICE, accessable: false },
          { id: ROUTE_IDS.GET_ONE_SERVICE, accessable: false },
          { id: ROUTE_IDS.CREATE_SERVICE, accessable: false },
          { id: ROUTE_IDS.GET_LIST_SUBSCRIPTION, accessable: false },
          { id: ROUTE_IDS.GET_ONE_SUBSCRIPTION, accessable: false },
        ],
      },
    ];

    records.forEach(async (record) => {
      await db.query({
        query: `insert ${JSON.stringify(record)} into @@model`,
        bindVars: {
          "@model": "permissions",
        },
      });
    });
    console.log("success seed tisc permssion data");
  };
  try {
    await createAndSeed(permissionCollection);
  } catch (error) {
    if (error.message === "duplicate name") {
      await permissionCollection.drop();
      await createAndSeed(permissionCollection);
    }
  }
};

module.exports = {
  seed,
};
