const { Database } = require("arangojs");
const dotenv = require("dotenv");
const moment = require("moment");
const uuid = require("uuid").v4;
const ROLES = require("./constant").ROLES;
const PERMISSION_TITLE = require("./constant").PERMISSION_TITLE;
dotenv.config();

const db = new Database({
  url: process.env.DATABASE_HOSTNAME,
});
db.useDatabase(process.env.DATABASE_NAME || "");
db.useBasicAuth(process.env.DATABASE_USERNAME, process.env.DATABASE_PASSWORD);

const seed = async () => {
  const collection = await db.collection("permissions");
  const createAndSeed = async (collection) => {
    await collection.create();
    await collection.get();
    const records = [
      {
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/my_workspace.png",
        name: PERMISSION_TITLE.MY_WORKSPACE,
        display: true,
        url: "",
        created_at: moment(),
        number: 1,
        parent_number: null,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/user_group.png",
        name: PERMISSION_TITLE.USER_GROUP,
        display: null,
        url: "",
        created_at: moment(),
        number: 2,
        parent_number: null,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/brand.png",
        name: PERMISSION_TITLE.USER_GROUP_BRAND,
        display: true,
        url: "",
        created_at: moment(),
        number: 3,
        parent_number: 2,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/design.png",
        name: PERMISSION_TITLE.USER_GROUP_DESIGN,
        display: true,
        url: "",
        created_at: moment(),
        number: 4,
        parent_number: 2,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/project.png",
        name: PERMISSION_TITLE.PROJECT,
        display: null,
        url: "",
        created_at: moment(),
        number: 5,
        parent_number: null,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/list.png",
        name: PERMISSION_TITLE.PROJECT_LIST,
        display: true,
        url: "",
        created_at: moment(),
        number: 6,
        parent_number: 5,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/product.png",
        name: PERMISSION_TITLE.PRODUCT,
        display: null,
        url: "",
        created_at: moment(),
        number: 7,
        parent_number: null,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/category.png",
        name: PERMISSION_TITLE.PRODUCT_CATEGORY,
        display: true,
        url: "",
        created_at: moment(),
        number: 8,
        parent_number: 7,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/basis.png",
        name: PERMISSION_TITLE.PRODUCT_BASIS,
        display: true,
        url: "",
        created_at: moment(),
        number: 9,
        parent_number: 7,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/attribute.png",
        name: PERMISSION_TITLE.PRODUCT_ATTRIBUTE,
        display: true,
        url: "",
        created_at: moment(),
        number: 10,
        parent_number: 7,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/configuration.png",
        name: PERMISSION_TITLE.PRODUCT_CONFIGURATION,
        display: true,
        url: "",
        created_at: moment(),
        number: 11,
        parent_number: 7,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/administration.png",
        name: PERMISSION_TITLE.ADMINISTRATION,
        display: null,
        url: "",
        created_at: moment(),
        number: 12,
        parent_number: null,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/documentation.png",
        name: PERMISSION_TITLE.ADMINISTRATION_DOCUMENTATION,
        display: true,
        url: "",
        created_at: moment(),
        number: 13,
        parent_number: 12,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/location.png",
        name: PERMISSION_TITLE.ADMINISTRATION_LOCATION,
        display: true,
        url: "",
        created_at: moment(),
        number: 14,
        parent_number: 12,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/team_profile.png",
        name: PERMISSION_TITLE.ADMINISTRATION_TEAM_PROFILE,
        display: true,
        url: "",
        created_at: moment(),
        number: 15,
        parent_number: 12,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/message.png",
        name: PERMISSION_TITLE.ADMINISTRATION_MESSAGE,
        display: true,
        url: "",
        created_at: moment(),
        number: 16,
        parent_number: 12,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_ADMIN,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/revenue.png",
        name: PERMISSION_TITLE.ADMINISTRATION_REVENUE,
        display: true,
        url: "",
        created_at: moment(),
        number: 17,
        parent_number: 12,
      },
      //consultant team
      {
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/my_workspace.png",
        name: PERMISSION_TITLE.MY_WORKSPACE,
        display: true,
        url: "",
        created_at: moment(),
        number: 1,
        parent_number: null,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/user_group.png",
        name: PERMISSION_TITLE.USER_GROUP,
        display: null,
        url: "",
        created_at: moment(),
        number: 2,
        parent_number: null,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/brand.png",
        name: PERMISSION_TITLE.USER_GROUP_BRAND,
        display: false,
        url: "",
        created_at: moment(),
        number: 3,
        parent_number: 2,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/design.png",
        name: PERMISSION_TITLE.USER_GROUP_DESIGN,
        display: false,
        url: "",
        created_at: moment(),
        number: 4,
        parent_number: 2,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/project.png",
        name: PERMISSION_TITLE.PROJECT,
        display: null,
        url: "",
        created_at: moment(),
        number: 5,
        parent_number: null,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/list.png",
        name: PERMISSION_TITLE.PROJECT_LIST,
        display: false,
        url: "",
        created_at: moment(),
        number: 6,
        parent_number: 5,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/product.png",
        name: PERMISSION_TITLE.PRODUCT,
        display: null,
        url: "",
        created_at: moment(),
        number: 7,
        parent_number: null,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/category.png",
        name: PERMISSION_TITLE.PRODUCT_CATEGORY,
        display: false,
        url: "",
        created_at: moment(),
        number: 8,
        parent_number: 7,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/basis.png",
        name: PERMISSION_TITLE.PRODUCT_BASIS,
        display: false,
        url: "",
        created_at: moment(),
        number: 9,
        parent_number: 7,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/attribute.png",
        name: PERMISSION_TITLE.PRODUCT_ATTRIBUTE,
        display: true,
        url: "",
        created_at: moment(),
        number: 10,
        parent_number: 7,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/configuration.png",
        name: PERMISSION_TITLE.PRODUCT_CONFIGURATION,
        display: true,
        url: "",
        created_at: moment(),
        number: 11,
        parent_number: 7,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/administration.png",
        name: PERMISSION_TITLE.ADMINISTRATION,
        display: null,
        url: "",
        created_at: moment(),
        number: 12,
        parent_number: null,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/documentation.png",
        name: PERMISSION_TITLE.ADMINISTRATION_DOCUMENTATION,
        display: false,
        url: "",
        created_at: moment(),
        number: 13,
        parent_number: 12,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/location.png",
        name: PERMISSION_TITLE.ADMINISTRATION_LOCATION,
        display: false,
        url: "",
        created_at: moment(),
        number: 14,
        parent_number: 12,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/team_profile.png",
        name: PERMISSION_TITLE.ADMINISTRATION_TEAM_PROFILE,
        display: false,
        url: "",
        created_at: moment(),
        number: 15,
        parent_number: 12,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/message.png",
        name: PERMISSION_TITLE.ADMINISTRATION_MESSAGE,
        display: false,
        url: "",
        created_at: moment(),
        number: 16,
        parent_number: 12,
      },
      {
        id: uuid(),
        role_id: ROLES.TISC_CONSULTANT_TEAM,
        model: "tisc",
        relation_id: null,
        logo: "/public/logo/revenue.png",
        name: PERMISSION_TITLE.ADMINISTRATION_REVENUE,
        display: false,
        url: "",
        created_at: moment(),
        number: 17,
        parent_number: 12,
      },
    ];

    records.forEach(async (record) => {
      await db.query({
        query: `insert ${JSON.stringify(record)} into @@model`,
        bindVars: {
          "@model": "permissions",
        },
      });
    });
    console.log("success seed tisc permssion data");
  };
  try {
    await createAndSeed(collection);
  } catch (error) {
    if (error.message === "duplicate name") {
      await collection.drop();
      await createAndSeed(collection);
    }
  }
};

module.exports = {
  seedPermission: seed,
};
