const uuid = require("uuid").v4;
const moment = require("moment");
const UNIT_TYPE_NULL_ATTRIBUTES =
  require("./constant").UNIT_TYPE_NULL_ATTRIBUTES;

const seed = async (db) => {
  const unitTypeCollection = await db.collection("unit_types");
  const createAndSeed = async (collection) => {
    await collection.create();
    await collection.get();
    const records = [
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Not Applicable",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "AVGdAverage",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "BGdBag",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "BAdBale",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "BJdBand",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "BIdBar",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "BRdBarrel",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "2WdBin",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "BLdBlock",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "BFdBoard Feet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "BMdBolt",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "BOdBottle",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "BXdBox",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "BOWLdBowl",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "BKTdBucket",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "BNdBulk",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "BDdBundle",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "CNdCan",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "AVdCapsule",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "CGdCard",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "CTdCarton",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "CGdCartridge",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "CAdCase",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "CSdCassette",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "CMdCentimeter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "CXdCoil",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "CHdContainer",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "8CdCord",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "CNTdCount",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "CRTdCrate",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "CCdCubic Centimeter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "CFdCubic Feet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "CIdCubic Inche",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "CRdCubic Meter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "CYdCubic Yard",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "CUdCup",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "CLdCylinder",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "DIdDiameter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "DSdDisplay",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "DZdDozen",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "DRdDrum",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "EAdEach",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "FTdFeet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "GALdGallon",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "GAdGauge",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "GRNdGrain",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "GRdGram",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "GSdGross",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "HAdHank",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "INdInch",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "JRdJar",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "JUdJug",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "KEdKeg",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "KGdKilogram",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "KTdKit",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "LNGdLength",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "LCMdLinear Centimeter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "LFTdLinear Foot",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "LMdLinear Meter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "LYdLinear Yard",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "LKdLink",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "LTdLiter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "LOdLot",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "MRdMeter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "ORDdOrder",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "OZdOunce",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "PAKdPack",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "PKdPackage",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "PKTdPacket",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "PDdPad",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "PGdPage",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "PAdPail",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "PRdPair",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "PFdPallet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "PCdPiece",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "PTdPint",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "PPdPlate",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "LBdPound",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "QTdQuart",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "QRdQuarter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "RAdRack",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "RMdReam",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "REdReel",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "RODdRod",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "RLdRoll",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "SACdSachet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "SJdSack",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "STdSet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "SHdSheet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "SHTdSingle",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "SLdSleeve",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "SOdSpool",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "SFdSquare Foot",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "SMdSquare Meter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "SYdSquare Yard",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "STKdStack",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "U2dTablet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "TKdTank",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "TYdTray",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "TONdTon",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "TUBdTub",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "TBdTube",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "UNdUnit",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "VILdVial",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "YDdYard",
        design_id: "",
        created_at: moment(),
      },
    ];
    records.forEach(async (record) => {
      await db.query({
        query: `insert ${JSON.stringify(record)} into @@model`,
        bindVars: {
          "@model": "unit_types",
        },
      });
    });
    console.log("success seed unit type data");
  };
  try {
    await createAndSeed(unitTypeCollection);
  } catch (error) {
    if (error.message === "duplicate name") {
      await unitTypeCollection.drop();
      await createAndSeed(unitTypeCollection);
    }
  }
};

module.exports = {
  seed,
};
