const uuid = require("uuid").v4;
const moment = require("moment");
const UNIT_TYPE_NULL_ATTRIBUTES =
  require("./constant").UNIT_TYPE_NULL_ATTRIBUTES;

const seed = async (db) => {
  const unitTypeCollection = await db.collection("unit_types");
  const createAndSeed = async (collection) => {
    await collection.create();
    await collection.get();
    const records = [
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Not Applicable",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Average",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Bag",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Bale",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Band",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Bar",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Barrel",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Bin",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Block",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Board Feet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Bolt",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Bottle",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Box",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Bowl",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Bucket",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Bulk",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Bundle",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Can",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Capsule",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Card",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Carton",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Cartridge",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Case",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Cassette",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Centimeter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Coil",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Container",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Cord",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Count",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Crate",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Cubic Centimeter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Cubic Feet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Cubic Inche",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Cubic Meter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Cubic Yard",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Cup",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Cylinder",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Diameter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Display",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Dozen",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Drum",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Each",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Feet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Gallon",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Gauge",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Grain",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Gram",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Gross",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Hank",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Inch",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Jar",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Jug",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Keg",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Kilogram",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Kit",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Length",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Linear Centimeter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Linear Foot",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Linear Meter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Linear Yard",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Link",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Liter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Lot",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Meter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Order",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Ounce",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Pack",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Package",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Packet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Pad",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Page",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Pail",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Pair",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Pallet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Piece",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Pint",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Plate",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Pound",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Quart",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Quarter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Rack",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Ream",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Reel",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Rod",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Roll",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Sachet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Sack",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Set",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Sheet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Single",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Sleeve",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Spool",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Square Foot",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Square Meter",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Square Yard",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Stack",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Tablet",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Tank",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Tray",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Ton",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Tub",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Tube",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Unit",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Vial",
        design_id: "",
        created_at: moment(),
      },
      {
        ...UNIT_TYPE_NULL_ATTRIBUTES,
        id: uuid(),
        name: "Yard",
        design_id: "",
        created_at: moment(),
      },
    ];
    records.forEach(async (record) => {
      await db.query({
        query: `insert ${JSON.stringify(record)} into @@model`,
        bindVars: {
          "@model": "unit_types",
        },
      });
    });
    console.log("success seed unit type data");
  };
  try {
    await createAndSeed(unitTypeCollection);
  } catch (error) {
    if (error.message === "duplicate name") {
      await unitTypeCollection.drop();
      await createAndSeed(unitTypeCollection);
    }
  }
};

module.exports = {
  seed,
};
