export const tiscAdminData = {
  role_id: "4fb9a23d-d60a-45a4-8ed4-2300276bc19b",
  firstname: "Tisc",
  lastname: "Admin",
  gender: true,
  location_id: "LOCATION-BRAND-TESTING-XXXX-XXXX",
  work_location: null,
  department_id: null,
  position: "",
  email: "tisc.admin@yopmail.com",
  phone_code: "",
  phone: "",
  mobile: "",
  password: "$2a$09$Uk42d5scAMr8MkxbzTTsceXpsouiX4aKFXL4NHQ6b.HHBI23rpIgS", // = "password"
  avatar: null,
  backup_email: "",
  personal_mobile: "",
  linkedin: "",
  is_verified: true,
  verification_token: null,
  reset_password_token: null,
  status: 1,
  type: 1,
  relation_id: "TISC",
  retrieve_favourite: false,
  interested: [],
  id: "USER-TISC-TESTING-XXXX",
  created_at: "2022-10-24 09:32:54",
  updated_at: "2022-10-24 09:33:46",
  deleted_at: null,
};
