import * as HapiJoi from "joi";
const Joi = HapiJoi.defaults((schema) => schema.options({ abortEarly: false }));
export default {
  countries: Joi.object({
    statusCode: Joi.number(),
    data: Joi.array().items(
      Joi.object({
        id: Joi.string(),
        name: Joi.string(),
        iso3: Joi.string(),
        iso2: Joi.string(),
        numeric_code: Joi.any(),
        phone_code: Joi.string(),
        capital: Joi.any(),
        currency: Joi.string(),
        currency_name: Joi.string(),
        currency_symbol: Joi.string(),
        tld: Joi.string(),
        native: Joi.any(),
        region: Joi.any(),
        subregion: Joi.any(),
        timezones: Joi.string(),
        latitude: Joi.number(),
        longitude: Joi.number(),
        emoji: Joi.string(),
        emojiU: Joi.string(),
      })
    ),
  }) as any,
  country: Joi.object({
    statusCode: Joi.number(),
    data: Joi.object({
      id: Joi.string(),
      name: Joi.string(),
      iso3: Joi.string(),
      iso2: Joi.string(),
      numeric_code: Joi.any(),
      phone_code: Joi.string(),
      capital: Joi.any(),
      currency: Joi.string(),
      currency_name: Joi.string(),
      currency_symbol: Joi.string(),
      tld: Joi.string(),
      native: Joi.any(),
      region: Joi.any(),
      subregion: Joi.any(),
      timezones: Joi.string(),
      latitude: Joi.number(),
      longitude: Joi.number(),
      emoji: Joi.string(),
      emojiU: Joi.string(),
    }),
  }) as any,
  states: Joi.object({
    statusCode: Joi.number(),
    data: Joi.array().items(
      Joi.object({
        id: Joi.string(),
        name: Joi.string(),
        country_id: Joi.string(),
        country_code: Joi.string(),
        country_name: Joi.string(),
        state_code: Joi.string(),
        type: Joi.any(),
        latitude: Joi.number(),
        longitude: Joi.number(),
      })
    ),
  }) as any,
  state: Joi.object({
    statusCode: Joi.number(),
    data: Joi.object({
      id: Joi.string(),
      name: Joi.string(),
      country_id: Joi.string(),
      country_code: Joi.string(),
      country_name: Joi.string(),
      state_code: Joi.string(),
      type: Joi.any(),
      latitude: Joi.number(),
      longitude: Joi.number(),
    }),
  }) as any,
  cities: Joi.object({
    statusCode: Joi.number(),
    data: Joi.array().items(
      Joi.object({
        id: Joi.string(),
        name: Joi.string(),
        state_id: Joi.string(),
        state_code: Joi.string(),
        state_name: Joi.string(),
        country_id: Joi.string(),
        country_code: Joi.string(),
        country_name: Joi.string(),
        latitude: Joi.number(),
        longitude: Joi.number(),
        wikiDataId: Joi.string(),
      })
    ),
  }) as any,
  city: Joi.object({
    statusCode: Joi.number(),
    data: Joi.object({
      id: Joi.string(),
      name: Joi.string(),
      state_id: Joi.string(),
      state_code: Joi.string(),
      state_name: Joi.string(),
      country_id: Joi.string(),
      country_code: Joi.string(),
      country_name: Joi.string(),
      latitude: Joi.number(),
      longitude: Joi.number(),
      wikiDataId: Joi.string(),
    }),
  }) as any,
  getOne: Joi.object({
    statusCode: Joi.number(),
    data: Joi.object({
      id: Joi.string(),
      business_name: Joi.string(),
      business_number: Joi.string(),
      functional_types: Joi.array().items({
        id: Joi.string(),
        name: Joi.string(),
      }),
      country_id: Joi.string(),
      state_id: Joi.any(),
      city_id: Joi.any(),
      country_name: Joi.string(),
      state_name: Joi.any(),
      city_name: Joi.any(),
      address: Joi.string(),
      postal_code: Joi.string(),
      general_phone: Joi.string(),
      general_email: Joi.string(),
      created_at: Joi.string(),
      phone_code: Joi.string(),
    }),
  }) as any,
  getList: Joi.object({
    statusCode: Joi.number(),
    data: Joi.object({
      locations: Joi.array().items(
        Joi.object({
          id: Joi.string(),
          business_name: Joi.string(),
          functional_types: Joi.array().items({
            id: Joi.string(),
            name: Joi.string(),
          }),
          country_name: Joi.string(),
          state_name: Joi.any(),
          city_name: Joi.any(),
          general_phone: Joi.string(),
          general_email: Joi.string(),
          created_at: Joi.string(),
          phone_code: Joi.string(),
          teams: Joi.number(),
        })
      ),
      pagination: Joi.object({
        page: Joi.number(),
        page_size: Joi.number(),
        total: Joi.number(),
        page_count: Joi.number(),
      }),
    }),
  }) as any,
  getListWithGroup: Joi.object({
    statusCode: Joi.number(),
    data: Joi.array().items({
      country_name: Joi.string(),
      count: Joi.number(),
      locations: Joi.array().items(
        Joi.object({
          id: Joi.string(),
          business_name: Joi.string(),
          functional_types: Joi.array().items({
            id: Joi.string(),
            name: Joi.string(),
          }),
          country_id: Joi.any(),
          state_id: Joi.any(),
          city_id: Joi.any(),
          country_name: Joi.string(),
          state_name: Joi.any(),
          city_name: Joi.any(),
          general_phone: Joi.string(),
          general_email: Joi.string(),
          created_at: Joi.string(),
          phone_code: Joi.string(),
          postal_code: Joi.string(),
          address: Joi.string(),
        })
      ),
    }),
  }) as any,
  getlistFunctionalType: Joi.object({
    statusCode: Joi.number(),
    data: Joi.array().items({
      id: Joi.string(),
      name: Joi.string(),
    }),
  }) as any,
};
