import * as Hapi from "@hapi/hapi";
import AuthRoute from "./api/auth/auth.route";
import ContactRoute from "./api/contact/contact.route";
import DocumentationRoute from "./api/documentation/documentation.route";
import UserRoute from "./api/user/user.route";
import BrandRoute from "./api/brand/brand.route";
import DesignerRoute from "./api/designer/designer.route";
import PermissionRoute from "./api/permission/permission.route";
import CollectionRoute from "./api/collection/collection.route";
import ProductRoute from "./api/product/product.route";
import CategoryRoute from "./api/category/category.route";
import AttributeRoute from "./api/attribute/attribute.route";
import BasisRoute from "./api/basis/basis.route";
import LocationRoute from "./api/location/location.route";
import QuotationRoute from "./api/quotation/quotation.route";
import AutoEmailRoute from "./api/auto_email/auto_email.route";
import DistributorRoute from "./api/distributor/distributor.route";
import MarketAvailabilityRoute from "./api/market_availability/market_availability.route";
import ProjectRoute from "./api/project/project.route";
import ProjectZoneRoute from "./api/project_zone/project_zone.route";
import MaterialCodeRoute from "./api/material_code/material_code.route";
import FavouriteRoute from "./api/favourite/favourite.route";
import UserProductSpecificationRoute from "./api/user_product_specification/user_product_specification.route";
import ProjectProductRoute from "./api/project_product/project_product.route";
import SettingRoute from "./api/setting/setting.route";
import PDFRoute from "./api/pdf/pdf.route";
import GeneralInquiryRoute from "./api/general_inquiry/general_inquiry.route";
import ProjectTrackingRoute from "./api/project_tracking/project_tracking.route";
import ActionTaskRoute from "./api/action_task/action_task.route";
import InvoiceRoute from "./api/invoice/invoice.route";
import CustomProductRoute from "./api/custom_product/custom_product.route";
import CustomResourceRoute from "./api/custom_resource/custom_resource.route";

export default class Router {
  public static async loadRoute(server: Hapi.Server): Promise<any> {
    await new AuthRoute().register(server);
    await new DocumentationRoute().register(server);
    await new UserRoute().register(server);
    await new ContactRoute().register(server);
    await new BrandRoute().register(server);
    await new DesignerRoute().register(server);
    await new PermissionRoute().register(server);
    await new CollectionRoute().register(server);
    await new ProductRoute().register(server);
    await new CategoryRoute().register(server);
    await new AttributeRoute().register(server);
    await new BasisRoute().register(server);
    await new LocationRoute().register(server);
    await new QuotationRoute().register(server);
    await new AutoEmailRoute().register(server);
    await new DistributorRoute().register(server);
    await new MarketAvailabilityRoute().register(server);
    await new ProjectRoute().register(server);
    await new ProjectZoneRoute().register(server);
    await new MaterialCodeRoute().register(server);
    await new FavouriteRoute().register(server);
    await new UserProductSpecificationRoute().register(server);
    await new ProjectProductRoute().register(server);
    await new SettingRoute().register(server);
    await new PDFRoute().register(server);
    await new GeneralInquiryRoute().register(server);
    await new ProjectTrackingRoute().register(server);
    await new ActionTaskRoute().register(server);
    await new InvoiceRoute().register(server);
    await new CustomProductRoute().register(server);
    await new CustomResourceRoute().register(server);
  }
}
